// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ums/v1/spine.proto

package umsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QoS defines quality of service class
type QoS int32

const (
	QoS_QOS_UNSPECIFIED QoS = 0
	QoS_QOS_COMMAND     QoS = 1 // At-least-once, durable, never drop unless expired
	QoS_QOS_CONTROL     QoS = 2 // At-least-once, durable, can be collapsed
	QoS_QOS_TELEMETRY   QoS = 3 // Best-effort, drop-first under backpressure
)

// Enum value maps for QoS.
var (
	QoS_name = map[int32]string{
		0: "QOS_UNSPECIFIED",
		1: "QOS_COMMAND",
		2: "QOS_CONTROL",
		3: "QOS_TELEMETRY",
	}
	QoS_value = map[string]int32{
		"QOS_UNSPECIFIED": 0,
		"QOS_COMMAND":     1,
		"QOS_CONTROL":     2,
		"QOS_TELEMETRY":   3,
	}
)

func (x QoS) Enum() *QoS {
	p := new(QoS)
	*p = x
	return p
}

func (x QoS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QoS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ums_v1_spine_proto_enumTypes[0].Descriptor()
}

func (QoS) Type() protoreflect.EnumType {
	return &file_proto_ums_v1_spine_proto_enumTypes[0]
}

func (x QoS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QoS.Descriptor instead.
func (QoS) EnumDescriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{0}
}

// TargetType defines mailbox target types
type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_SERVER      TargetType = 1
	TargetType_TARGET_TYPE_CLUSTER     TargetType = 2
	TargetType_TARGET_TYPE_ORG         TargetType = 3
	TargetType_TARGET_TYPE_SERVICE     TargetType = 4
	TargetType_TARGET_TYPE_BROADCAST   TargetType = 5
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_SERVER",
		2: "TARGET_TYPE_CLUSTER",
		3: "TARGET_TYPE_ORG",
		4: "TARGET_TYPE_SERVICE",
		5: "TARGET_TYPE_BROADCAST",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_SERVER":      1,
		"TARGET_TYPE_CLUSTER":     2,
		"TARGET_TYPE_ORG":         3,
		"TARGET_TYPE_SERVICE":     4,
		"TARGET_TYPE_BROADCAST":   5,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ums_v1_spine_proto_enumTypes[1].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_proto_ums_v1_spine_proto_enumTypes[1]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{1}
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Ack
	//	*ClientFrame_AckSet
	//	*ClientFrame_Subscribe
	//	*ClientFrame_Ping
	//	*ClientFrame_FlowHint
	//	*ClientFrame_Nack
	Frame         isClientFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetFrame() isClientFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClientFrame) GetHello() *HelloFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetAck() *AckFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ClientFrame) GetAckSet() *AckSetFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_AckSet); ok {
			return x.AckSet
		}
	}
	return nil
}

func (x *ClientFrame) GetSubscribe() *SubscribeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientFrame) GetFlowHint() *FlowHintFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_FlowHint); ok {
			return x.FlowHint
		}
	}
	return nil
}

func (x *ClientFrame) GetNack() *NackFrame {
	if x != nil {
		if x, ok := x.Frame.(*ClientFrame_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isClientFrame_Frame interface {
	isClientFrame_Frame()
}

type ClientFrame_Hello struct {
	Hello *HelloFrame `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Ack struct {
	Ack *AckFrame `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ClientFrame_AckSet struct {
	AckSet *AckSetFrame `protobuf:"bytes,3,opt,name=ack_set,json=ackSet,proto3,oneof"`
}

type ClientFrame_Subscribe struct {
	Subscribe *SubscribeFrame `protobuf:"bytes,4,opt,name=subscribe,proto3,oneof"`
}

type ClientFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type ClientFrame_FlowHint struct {
	FlowHint *FlowHintFrame `protobuf:"bytes,6,opt,name=flow_hint,json=flowHint,proto3,oneof"`
}

type ClientFrame_Nack struct {
	Nack *NackFrame `protobuf:"bytes,7,opt,name=nack,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Frame() {}

func (*ClientFrame_Ack) isClientFrame_Frame() {}

func (*ClientFrame_AckSet) isClientFrame_Frame() {}

func (*ClientFrame_Subscribe) isClientFrame_Frame() {}

func (*ClientFrame_Ping) isClientFrame_Frame() {}

func (*ClientFrame_FlowHint) isClientFrame_Frame() {}

func (*ClientFrame_Nack) isClientFrame_Frame() {}

// HelloFrame is the first frame sent by client to establish session
type HelloFrame struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion         string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerId                string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // Stable Underleaf identity
	OrgId                   string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DeviceFingerprint       string                 `protobuf:"bytes,4,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`                                                                   // TPM/SW attestation hash (optional)
	CapabilitiesSummaryHash string                 `protobuf:"bytes,5,opt,name=capabilities_summary_hash,json=capabilitiesSummaryHash,proto3" json:"capabilities_summary_hash,omitempty"`                                               // For future optimization
	ResumeToken             string                 `protobuf:"bytes,6,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`                                                                                     // For session resumption
	ClientFeatures          map[string]bool        `protobuf:"bytes,7,rep,name=client_features,json=clientFeatures,proto3" json:"client_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // supports_compression, supports_batch_ack, etc.
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HelloFrame) Reset() {
	*x = HelloFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloFrame) ProtoMessage() {}

func (x *HelloFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloFrame.ProtoReflect.Descriptor instead.
func (*HelloFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{1}
}

func (x *HelloFrame) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HelloFrame) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HelloFrame) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *HelloFrame) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *HelloFrame) GetCapabilitiesSummaryHash() string {
	if x != nil {
		return x.CapabilitiesSummaryHash
	}
	return ""
}

func (x *HelloFrame) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *HelloFrame) GetClientFeatures() map[string]bool {
	if x != nil {
		return x.ClientFeatures
	}
	return nil
}

// AckFrame acknowledges cumulative delivery up to seq
type AckFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	SeqAcked      uint64                 `protobuf:"varint,2,opt,name=seq_acked,json=seqAcked,proto3" json:"seq_acked,omitempty"` // All seq <= seq_acked are processed and committed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckFrame) Reset() {
	*x = AckFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckFrame) ProtoMessage() {}

func (x *AckFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckFrame.ProtoReflect.Descriptor instead.
func (*AckFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{2}
}

func (x *AckFrame) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *AckFrame) GetSeqAcked() uint64 {
	if x != nil {
		return x.SeqAcked
	}
	return 0
}

// AckSetFrame acknowledges selective sequence numbers (out-of-order processing)
type AckSetFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Seqs          []uint64               `protobuf:"varint,2,rep,packed,name=seqs,proto3" json:"seqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckSetFrame) Reset() {
	*x = AckSetFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckSetFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckSetFrame) ProtoMessage() {}

func (x *AckSetFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckSetFrame.ProtoReflect.Descriptor instead.
func (*AckSetFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{3}
}

func (x *AckSetFrame) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *AckSetFrame) GetSeqs() []uint64 {
	if x != nil {
		return x.Seqs
	}
	return nil
}

// SubscribeFrame subscribes to mailboxes by target
type SubscribeFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Targets        []*Target              `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Filters        map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional filters (discouraged)
	QosPreferences *QoSPreferences        `protobuf:"bytes,3,opt,name=qos_preferences,json=qosPreferences,proto3" json:"qos_preferences,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeFrame) Reset() {
	*x = SubscribeFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFrame) ProtoMessage() {}

func (x *SubscribeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFrame.ProtoReflect.Descriptor instead.
func (*SubscribeFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeFrame) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SubscribeFrame) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SubscribeFrame) GetQosPreferences() *QoSPreferences {
	if x != nil {
		return x.QosPreferences
	}
	return nil
}

type QoSPreferences struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TelemetryDisabled bool                   `protobuf:"varint,1,opt,name=telemetry_disabled,json=telemetryDisabled,proto3" json:"telemetry_disabled,omitempty"`
	ControlCollapsed  bool                   `protobuf:"varint,2,opt,name=control_collapsed,json=controlCollapsed,proto3" json:"control_collapsed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QoSPreferences) Reset() {
	*x = QoSPreferences{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QoSPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QoSPreferences) ProtoMessage() {}

func (x *QoSPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QoSPreferences.ProtoReflect.Descriptor instead.
func (*QoSPreferences) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{5}
}

func (x *QoSPreferences) GetTelemetryDisabled() bool {
	if x != nil {
		return x.TelemetryDisabled
	}
	return false
}

func (x *QoSPreferences) GetControlCollapsed() bool {
	if x != nil {
		return x.ControlCollapsed
	}
	return false
}

// PingFrame for heartbeat
type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{6}
}

func (x *PingFrame) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

// FlowHintFrame indicates client backpressure state
type FlowHintFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hint          string                 `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"` // "overloaded", "reduce_telemetry", "pause_control", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowHintFrame) Reset() {
	*x = FlowHintFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowHintFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowHintFrame) ProtoMessage() {}

func (x *FlowHintFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowHintFrame.ProtoReflect.Descriptor instead.
func (*FlowHintFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{7}
}

func (x *FlowHintFrame) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

// NackFrame rejects an envelope (malformed, cannot process)
type NackFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackFrame) Reset() {
	*x = NackFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackFrame) ProtoMessage() {}

func (x *NackFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackFrame.ProtoReflect.Descriptor instead.
func (*NackFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{8}
}

func (x *NackFrame) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *NackFrame) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NackFrame) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ServerFrame_Welcome
	//	*ServerFrame_Deliver
	//	*ServerFrame_SubscribeOk
	//	*ServerFrame_Pong
	//	*ServerFrame_Error
	//	*ServerFrame_ResumeOk
	//	*ServerFrame_ResumeDenied
	Frame         isServerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{9}
}

func (x *ServerFrame) GetFrame() isServerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ServerFrame) GetWelcome() *WelcomeFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerFrame) GetDeliver() *DeliverFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Deliver); ok {
			return x.Deliver
		}
	}
	return nil
}

func (x *ServerFrame) GetSubscribeOk() *SubscribeOkFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_SubscribeOk); ok {
			return x.SubscribeOk
		}
	}
	return nil
}

func (x *ServerFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetResumeOk() *ResumeOkFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_ResumeOk); ok {
			return x.ResumeOk
		}
	}
	return nil
}

func (x *ServerFrame) GetResumeDenied() *ResumeDeniedFrame {
	if x != nil {
		if x, ok := x.Frame.(*ServerFrame_ResumeDenied); ok {
			return x.ResumeDenied
		}
	}
	return nil
}

type isServerFrame_Frame interface {
	isServerFrame_Frame()
}

type ServerFrame_Welcome struct {
	Welcome *WelcomeFrame `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerFrame_Deliver struct {
	Deliver *DeliverFrame `protobuf:"bytes,2,opt,name=deliver,proto3,oneof"`
}

type ServerFrame_SubscribeOk struct {
	SubscribeOk *SubscribeOkFrame `protobuf:"bytes,3,opt,name=subscribe_ok,json=subscribeOk,proto3,oneof"`
}

type ServerFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorFrame `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ServerFrame_ResumeOk struct {
	ResumeOk *ResumeOkFrame `protobuf:"bytes,6,opt,name=resume_ok,json=resumeOk,proto3,oneof"`
}

type ServerFrame_ResumeDenied struct {
	ResumeDenied *ResumeDeniedFrame `protobuf:"bytes,7,opt,name=resume_denied,json=resumeDenied,proto3,oneof"`
}

func (*ServerFrame_Welcome) isServerFrame_Frame() {}

func (*ServerFrame_Deliver) isServerFrame_Frame() {}

func (*ServerFrame_SubscribeOk) isServerFrame_Frame() {}

func (*ServerFrame_Pong) isServerFrame_Frame() {}

func (*ServerFrame_Error) isServerFrame_Frame() {}

func (*ServerFrame_ResumeOk) isServerFrame_Frame() {}

func (*ServerFrame_ResumeDenied) isServerFrame_Frame() {}

// WelcomeFrame is server's response to HelloFrame (new session)
type WelcomeFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionEpoch  uint64                 `protobuf:"varint,2,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	ResumeToken   string                 `protobuf:"bytes,3,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,4,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	Policy        *SessionPolicy         `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeFrame) Reset() {
	*x = WelcomeFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeFrame) ProtoMessage() {}

func (x *WelcomeFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeFrame.ProtoReflect.Descriptor instead.
func (*WelcomeFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{10}
}

func (x *WelcomeFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WelcomeFrame) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *WelcomeFrame) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *WelcomeFrame) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *WelcomeFrame) GetPolicy() *SessionPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// SessionPolicy defines limits and intervals for this session
type SessionPolicy struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MaxInflightTotal         int32                  `protobuf:"varint,1,opt,name=max_inflight_total,json=maxInflightTotal,proto3" json:"max_inflight_total,omitempty"`
	MaxInflightCommand       int32                  `protobuf:"varint,2,opt,name=max_inflight_command,json=maxInflightCommand,proto3" json:"max_inflight_command,omitempty"`
	MaxInflightControl       int32                  `protobuf:"varint,3,opt,name=max_inflight_control,json=maxInflightControl,proto3" json:"max_inflight_control,omitempty"`
	MaxInflightTelemetry     int32                  `protobuf:"varint,4,opt,name=max_inflight_telemetry,json=maxInflightTelemetry,proto3" json:"max_inflight_telemetry,omitempty"`
	MaxBatchBytes            int32                  `protobuf:"varint,5,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,6,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SessionPolicy) Reset() {
	*x = SessionPolicy{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPolicy) ProtoMessage() {}

func (x *SessionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPolicy.ProtoReflect.Descriptor instead.
func (*SessionPolicy) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{11}
}

func (x *SessionPolicy) GetMaxInflightTotal() int32 {
	if x != nil {
		return x.MaxInflightTotal
	}
	return 0
}

func (x *SessionPolicy) GetMaxInflightCommand() int32 {
	if x != nil {
		return x.MaxInflightCommand
	}
	return 0
}

func (x *SessionPolicy) GetMaxInflightControl() int32 {
	if x != nil {
		return x.MaxInflightControl
	}
	return 0
}

func (x *SessionPolicy) GetMaxInflightTelemetry() int32 {
	if x != nil {
		return x.MaxInflightTelemetry
	}
	return 0
}

func (x *SessionPolicy) GetMaxBatchBytes() int32 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

func (x *SessionPolicy) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

// DeliverFrame delivers one or more envelopes
type DeliverFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Envelopes     []*Envelope            `protobuf:"bytes,2,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverFrame) Reset() {
	*x = DeliverFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverFrame) ProtoMessage() {}

func (x *DeliverFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverFrame.ProtoReflect.Descriptor instead.
func (*DeliverFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverFrame) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DeliverFrame) GetEnvelopes() []*Envelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

// SubscribeOkFrame confirms subscription with resolved mailbox IDs
type SubscribeOkFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxIds    []string               `protobuf:"bytes,1,rep,name=mailbox_ids,json=mailboxIds,proto3" json:"mailbox_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOkFrame) Reset() {
	*x = SubscribeOkFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOkFrame) ProtoMessage() {}

func (x *SubscribeOkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOkFrame.ProtoReflect.Descriptor instead.
func (*SubscribeOkFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeOkFrame) GetMailboxIds() []string {
	if x != nil {
		return x.MailboxIds
	}
	return nil
}

// PongFrame is server's response to PingFrame
type PongFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTimeMs  int64                  `protobuf:"varint,1,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	ClientTimeMs  int64                  `protobuf:"varint,2,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"` // Echo back client's timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{14}
}

func (x *PongFrame) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *PongFrame) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

// ErrorFrame indicates an error condition
type ErrorFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorFrame) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorFrame) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// ResumeOkFrame indicates successful session resumption
type ResumeOkFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionEpoch  uint64                 `protobuf:"varint,2,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	ResumeToken   string                 `protobuf:"bytes,3,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`                                                                                 // New resume token
	LastAckedSeq  map[string]uint64      `protobuf:"bytes,4,rep,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // mailbox_id → seq
	Policy        *SessionPolicy         `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeOkFrame) Reset() {
	*x = ResumeOkFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeOkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeOkFrame) ProtoMessage() {}

func (x *ResumeOkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeOkFrame.ProtoReflect.Descriptor instead.
func (*ResumeOkFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeOkFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResumeOkFrame) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *ResumeOkFrame) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *ResumeOkFrame) GetLastAckedSeq() map[string]uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return nil
}

func (x *ResumeOkFrame) GetPolicy() *SessionPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

// ResumeDeniedFrame indicates failed session resumption
type ResumeDeniedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDeniedFrame) Reset() {
	*x = ResumeDeniedFrame{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDeniedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDeniedFrame) ProtoMessage() {}

func (x *ResumeDeniedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDeniedFrame.ProtoReflect.Descriptor instead.
func (*ResumeDeniedFrame) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeDeniedFrame) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Envelope is a single message unit
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvelopeId    string                 `protobuf:"bytes,1,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"` // UUID or ULID
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // Monotonic per mailbox
	Qos           QoS                    `protobuf:"varint,4,opt,name=qos,proto3,enum=ums.v1.QoS" json:"qos,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // e.g., "command.run", "deploy.apply", "config.delta"
	CreatedAtMs   int64                  `protobuf:"varint,6,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	ExpiresAtMs   int64                  `protobuf:"varint,7,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"` // Optional but recommended for commands
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`                              // JSON/protobuf/CBOR allowed
	DedupeKey     string                 `protobuf:"bytes,10,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`        // For idempotency
	Priority      int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`                          // Within QoS
	RequiresAck   bool                   `protobuf:"varint,12,opt,name=requires_ack,json=requiresAck,proto3" json:"requires_ack,omitempty"` // Default true for COMMAND/CONTROL, false for TELEMETRY
	OrgId         string                 `protobuf:"bytes,13,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                    // Multi-tenancy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{18}
}

func (x *Envelope) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *Envelope) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetQos() QoS {
	if x != nil {
		return x.Qos
	}
	return QoS_QOS_UNSPECIFIED
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Envelope) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *Envelope) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Envelope) GetRequiresAck() bool {
	if x != nil {
		return x.RequiresAck
	}
	return false
}

func (x *Envelope) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// Target identifies a routing destination
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetType    TargetType             `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=ums.v1.TargetType" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DeliverRole   string                 `protobuf:"bytes,4,opt,name=deliver_role,json=deliverRole,proto3" json:"deliver_role,omitempty"` // Optional: "LEADER" for cluster fanout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{19}
}

func (x *Target) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *Target) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Target) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Target) GetDeliverRole() string {
	if x != nil {
		return x.DeliverRole
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Targets       []*Target              `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{20}
}

func (x *PublishRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PublishRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MailboxSeqs   map[string]uint64      `protobuf:"bytes,3,rep,name=mailbox_seqs,json=mailboxSeqs,proto3" json:"mailbox_seqs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // mailbox_id → assigned seq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_ums_v1_spine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ums_v1_spine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_ums_v1_spine_proto_rawDescGZIP(), []int{21}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishResponse) GetMailboxSeqs() map[string]uint64 {
	if x != nil {
		return x.MailboxSeqs
	}
	return nil
}

var File_proto_ums_v1_spine_proto protoreflect.FileDescriptor

const file_proto_ums_v1_spine_proto_rawDesc = "" +
	"\n" +
	"\x18proto/ums/v1/spine.proto\x12\x06ums.v1\"\xd8\x02\n" +
	"\vClientFrame\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.ums.v1.HelloFrameH\x00R\x05hello\x12$\n" +
	"\x03ack\x18\x02 \x01(\v2\x10.ums.v1.AckFrameH\x00R\x03ack\x12.\n" +
	"\aack_set\x18\x03 \x01(\v2\x13.ums.v1.AckSetFrameH\x00R\x06ackSet\x126\n" +
	"\tsubscribe\x18\x04 \x01(\v2\x16.ums.v1.SubscribeFrameH\x00R\tsubscribe\x12'\n" +
	"\x04ping\x18\x05 \x01(\v2\x11.ums.v1.PingFrameH\x00R\x04ping\x124\n" +
	"\tflow_hint\x18\x06 \x01(\v2\x15.ums.v1.FlowHintFrameH\x00R\bflowHint\x12'\n" +
	"\x04nack\x18\a \x01(\v2\x11.ums.v1.NackFrameH\x00R\x04nackB\a\n" +
	"\x05frame\"\x8d\x03\n" +
	"\n" +
	"HelloFrame\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12-\n" +
	"\x12device_fingerprint\x18\x04 \x01(\tR\x11deviceFingerprint\x12:\n" +
	"\x19capabilities_summary_hash\x18\x05 \x01(\tR\x17capabilitiesSummaryHash\x12!\n" +
	"\fresume_token\x18\x06 \x01(\tR\vresumeToken\x12O\n" +
	"\x0fclient_features\x18\a \x03(\v2&.ums.v1.HelloFrame.ClientFeaturesEntryR\x0eclientFeatures\x1aA\n" +
	"\x13ClientFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"F\n" +
	"\bAckFrame\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x1b\n" +
	"\tseq_acked\x18\x02 \x01(\x04R\bseqAcked\"@\n" +
	"\vAckSetFrame\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x12\n" +
	"\x04seqs\x18\x02 \x03(\x04R\x04seqs\"\xf6\x01\n" +
	"\x0eSubscribeFrame\x12(\n" +
	"\atargets\x18\x01 \x03(\v2\x0e.ums.v1.TargetR\atargets\x12=\n" +
	"\afilters\x18\x02 \x03(\v2#.ums.v1.SubscribeFrame.FiltersEntryR\afilters\x12?\n" +
	"\x0fqos_preferences\x18\x03 \x01(\v2\x16.ums.v1.QoSPreferencesR\x0eqosPreferences\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x0eQoSPreferences\x12-\n" +
	"\x12telemetry_disabled\x18\x01 \x01(\bR\x11telemetryDisabled\x12+\n" +
	"\x11control_collapsed\x18\x02 \x01(\bR\x10controlCollapsed\"1\n" +
	"\tPingFrame\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\"#\n" +
	"\rFlowHintFrame\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\"T\n" +
	"\tNackFrame\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x86\x03\n" +
	"\vServerFrame\x120\n" +
	"\awelcome\x18\x01 \x01(\v2\x14.ums.v1.WelcomeFrameH\x00R\awelcome\x120\n" +
	"\adeliver\x18\x02 \x01(\v2\x14.ums.v1.DeliverFrameH\x00R\adeliver\x12=\n" +
	"\fsubscribe_ok\x18\x03 \x01(\v2\x18.ums.v1.SubscribeOkFrameH\x00R\vsubscribeOk\x12'\n" +
	"\x04pong\x18\x04 \x01(\v2\x11.ums.v1.PongFrameH\x00R\x04pong\x12*\n" +
	"\x05error\x18\x05 \x01(\v2\x12.ums.v1.ErrorFrameH\x00R\x05error\x124\n" +
	"\tresume_ok\x18\x06 \x01(\v2\x15.ums.v1.ResumeOkFrameH\x00R\bresumeOk\x12@\n" +
	"\rresume_denied\x18\a \x01(\v2\x19.ums.v1.ResumeDeniedFrameH\x00R\fresumeDeniedB\a\n" +
	"\x05frame\"\xca\x01\n" +
	"\fWelcomeFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x02 \x01(\x04R\fsessionEpoch\x12!\n" +
	"\fresume_token\x18\x03 \x01(\tR\vresumeToken\x12$\n" +
	"\x0eserver_time_ms\x18\x04 \x01(\x03R\fserverTimeMs\x12-\n" +
	"\x06policy\x18\x05 \x01(\v2\x15.ums.v1.SessionPolicyR\x06policy\"\xbd\x02\n" +
	"\rSessionPolicy\x12,\n" +
	"\x12max_inflight_total\x18\x01 \x01(\x05R\x10maxInflightTotal\x120\n" +
	"\x14max_inflight_command\x18\x02 \x01(\x05R\x12maxInflightCommand\x120\n" +
	"\x14max_inflight_control\x18\x03 \x01(\x05R\x12maxInflightControl\x124\n" +
	"\x16max_inflight_telemetry\x18\x04 \x01(\x05R\x14maxInflightTelemetry\x12&\n" +
	"\x0fmax_batch_bytes\x18\x05 \x01(\x05R\rmaxBatchBytes\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x06 \x01(\x05R\x18heartbeatIntervalSeconds\"Y\n" +
	"\fDeliverFrame\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12.\n" +
	"\tenvelopes\x18\x02 \x03(\v2\x10.ums.v1.EnvelopeR\tenvelopes\"3\n" +
	"\x10SubscribeOkFrame\x12\x1f\n" +
	"\vmailbox_ids\x18\x01 \x03(\tR\n" +
	"mailboxIds\"W\n" +
	"\tPongFrame\x12$\n" +
	"\x0eserver_time_ms\x18\x01 \x01(\x03R\fserverTimeMs\x12$\n" +
	"\x0eclient_time_ms\x18\x02 \x01(\x03R\fclientTimeMs\"\xcf\x01\n" +
	"\n" +
	"ErrorFrame\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x129\n" +
	"\acontext\x18\x04 \x03(\v2\x1f.ums.v1.ErrorFrame.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x02\n" +
	"\rResumeOkFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_epoch\x18\x02 \x01(\x04R\fsessionEpoch\x12!\n" +
	"\fresume_token\x18\x03 \x01(\tR\vresumeToken\x12M\n" +
	"\x0elast_acked_seq\x18\x04 \x03(\v2'.ums.v1.ResumeOkFrame.LastAckedSeqEntryR\flastAckedSeq\x12-\n" +
	"\x06policy\x18\x05 \x01(\v2\x15.ums.v1.SessionPolicyR\x06policy\x1a?\n" +
	"\x11LastAckedSeqEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"+\n" +
	"\x11ResumeDeniedFrame\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x81\x03\n" +
	"\bEnvelope\x12\x1f\n" +
	"\venvelope_id\x18\x01 \x01(\tR\n" +
	"envelopeId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x1d\n" +
	"\x03qos\x18\x04 \x01(\x0e2\v.ums.v1.QoSR\x03qos\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\"\n" +
	"\rcreated_at_ms\x18\x06 \x01(\x03R\vcreatedAtMs\x12\"\n" +
	"\rexpires_at_ms\x18\a \x01(\x03R\vexpiresAtMs\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\n" +
	" \x01(\tR\tdedupeKey\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12!\n" +
	"\frequires_ack\x18\f \x01(\bR\vrequiresAck\x12\x15\n" +
	"\x06org_id\x18\r \x01(\tR\x05orgId\"\x94\x01\n" +
	"\x06Target\x123\n" +
	"\vtarget_type\x18\x01 \x01(\x0e2\x12.ums.v1.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12!\n" +
	"\fdeliver_role\x18\x04 \x01(\tR\vdeliverRole\"h\n" +
	"\x0ePublishRequest\x12,\n" +
	"\benvelope\x18\x01 \x01(\v2\x10.ums.v1.EnvelopeR\benvelope\x12(\n" +
	"\atargets\x18\x02 \x03(\v2\x0e.ums.v1.TargetR\atargets\"\xce\x01\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12K\n" +
	"\fmailbox_seqs\x18\x03 \x03(\v2(.ums.v1.PublishResponse.MailboxSeqsEntryR\vmailboxSeqs\x1a>\n" +
	"\x10MailboxSeqsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01*O\n" +
	"\x03QoS\x12\x13\n" +
	"\x0fQOS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vQOS_COMMAND\x10\x01\x12\x0f\n" +
	"\vQOS_CONTROL\x10\x02\x12\x11\n" +
	"\rQOS_TELEMETRY\x10\x03*\xa3\x01\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TARGET_TYPE_SERVER\x10\x01\x12\x17\n" +
	"\x13TARGET_TYPE_CLUSTER\x10\x02\x12\x13\n" +
	"\x0fTARGET_TYPE_ORG\x10\x03\x12\x17\n" +
	"\x13TARGET_TYPE_SERVICE\x10\x04\x12\x19\n" +
	"\x15TARGET_TYPE_BROADCAST\x10\x052F\n" +
	"\vSpineStream\x127\n" +
	"\aConnect\x12\x13.ums.v1.ClientFrame\x1a\x13.ums.v1.ServerFrame(\x010\x012J\n" +
	"\fSpinePublish\x12:\n" +
	"\aPublish\x12\x16.ums.v1.PublishRequest\x1a\x17.ums.v1.PublishResponseBCZAgithub.com/ambientlabscomputing/mycelium_spine/proto/ums/v1;umsv1b\x06proto3"

var (
	file_proto_ums_v1_spine_proto_rawDescOnce sync.Once
	file_proto_ums_v1_spine_proto_rawDescData []byte
)

func file_proto_ums_v1_spine_proto_rawDescGZIP() []byte {
	file_proto_ums_v1_spine_proto_rawDescOnce.Do(func() {
		file_proto_ums_v1_spine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ums_v1_spine_proto_rawDesc), len(file_proto_ums_v1_spine_proto_rawDesc)))
	})
	return file_proto_ums_v1_spine_proto_rawDescData
}

var file_proto_ums_v1_spine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ums_v1_spine_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_ums_v1_spine_proto_goTypes = []any{
	(QoS)(0),                  // 0: ums.v1.QoS
	(TargetType)(0),           // 1: ums.v1.TargetType
	(*ClientFrame)(nil),       // 2: ums.v1.ClientFrame
	(*HelloFrame)(nil),        // 3: ums.v1.HelloFrame
	(*AckFrame)(nil),          // 4: ums.v1.AckFrame
	(*AckSetFrame)(nil),       // 5: ums.v1.AckSetFrame
	(*SubscribeFrame)(nil),    // 6: ums.v1.SubscribeFrame
	(*QoSPreferences)(nil),    // 7: ums.v1.QoSPreferences
	(*PingFrame)(nil),         // 8: ums.v1.PingFrame
	(*FlowHintFrame)(nil),     // 9: ums.v1.FlowHintFrame
	(*NackFrame)(nil),         // 10: ums.v1.NackFrame
	(*ServerFrame)(nil),       // 11: ums.v1.ServerFrame
	(*WelcomeFrame)(nil),      // 12: ums.v1.WelcomeFrame
	(*SessionPolicy)(nil),     // 13: ums.v1.SessionPolicy
	(*DeliverFrame)(nil),      // 14: ums.v1.DeliverFrame
	(*SubscribeOkFrame)(nil),  // 15: ums.v1.SubscribeOkFrame
	(*PongFrame)(nil),         // 16: ums.v1.PongFrame
	(*ErrorFrame)(nil),        // 17: ums.v1.ErrorFrame
	(*ResumeOkFrame)(nil),     // 18: ums.v1.ResumeOkFrame
	(*ResumeDeniedFrame)(nil), // 19: ums.v1.ResumeDeniedFrame
	(*Envelope)(nil),          // 20: ums.v1.Envelope
	(*Target)(nil),            // 21: ums.v1.Target
	(*PublishRequest)(nil),    // 22: ums.v1.PublishRequest
	(*PublishResponse)(nil),   // 23: ums.v1.PublishResponse
	nil,                       // 24: ums.v1.HelloFrame.ClientFeaturesEntry
	nil,                       // 25: ums.v1.SubscribeFrame.FiltersEntry
	nil,                       // 26: ums.v1.ErrorFrame.ContextEntry
	nil,                       // 27: ums.v1.ResumeOkFrame.LastAckedSeqEntry
	nil,                       // 28: ums.v1.PublishResponse.MailboxSeqsEntry
}
var file_proto_ums_v1_spine_proto_depIdxs = []int32{
	3,  // 0: ums.v1.ClientFrame.hello:type_name -> ums.v1.HelloFrame
	4,  // 1: ums.v1.ClientFrame.ack:type_name -> ums.v1.AckFrame
	5,  // 2: ums.v1.ClientFrame.ack_set:type_name -> ums.v1.AckSetFrame
	6,  // 3: ums.v1.ClientFrame.subscribe:type_name -> ums.v1.SubscribeFrame
	8,  // 4: ums.v1.ClientFrame.ping:type_name -> ums.v1.PingFrame
	9,  // 5: ums.v1.ClientFrame.flow_hint:type_name -> ums.v1.FlowHintFrame
	10, // 6: ums.v1.ClientFrame.nack:type_name -> ums.v1.NackFrame
	24, // 7: ums.v1.HelloFrame.client_features:type_name -> ums.v1.HelloFrame.ClientFeaturesEntry
	21, // 8: ums.v1.SubscribeFrame.targets:type_name -> ums.v1.Target
	25, // 9: ums.v1.SubscribeFrame.filters:type_name -> ums.v1.SubscribeFrame.FiltersEntry
	7,  // 10: ums.v1.SubscribeFrame.qos_preferences:type_name -> ums.v1.QoSPreferences
	12, // 11: ums.v1.ServerFrame.welcome:type_name -> ums.v1.WelcomeFrame
	14, // 12: ums.v1.ServerFrame.deliver:type_name -> ums.v1.DeliverFrame
	15, // 13: ums.v1.ServerFrame.subscribe_ok:type_name -> ums.v1.SubscribeOkFrame
	16, // 14: ums.v1.ServerFrame.pong:type_name -> ums.v1.PongFrame
	17, // 15: ums.v1.ServerFrame.error:type_name -> ums.v1.ErrorFrame
	18, // 16: ums.v1.ServerFrame.resume_ok:type_name -> ums.v1.ResumeOkFrame
	19, // 17: ums.v1.ServerFrame.resume_denied:type_name -> ums.v1.ResumeDeniedFrame
	13, // 18: ums.v1.WelcomeFrame.policy:type_name -> ums.v1.SessionPolicy
	20, // 19: ums.v1.DeliverFrame.envelopes:type_name -> ums.v1.Envelope
	26, // 20: ums.v1.ErrorFrame.context:type_name -> ums.v1.ErrorFrame.ContextEntry
	27, // 21: ums.v1.ResumeOkFrame.last_acked_seq:type_name -> ums.v1.ResumeOkFrame.LastAckedSeqEntry
	13, // 22: ums.v1.ResumeOkFrame.policy:type_name -> ums.v1.SessionPolicy
	0,  // 23: ums.v1.Envelope.qos:type_name -> ums.v1.QoS
	1,  // 24: ums.v1.Target.target_type:type_name -> ums.v1.TargetType
	20, // 25: ums.v1.PublishRequest.envelope:type_name -> ums.v1.Envelope
	21, // 26: ums.v1.PublishRequest.targets:type_name -> ums.v1.Target
	28, // 27: ums.v1.PublishResponse.mailbox_seqs:type_name -> ums.v1.PublishResponse.MailboxSeqsEntry
	2,  // 28: ums.v1.SpineStream.Connect:input_type -> ums.v1.ClientFrame
	22, // 29: ums.v1.SpinePublish.Publish:input_type -> ums.v1.PublishRequest
	11, // 30: ums.v1.SpineStream.Connect:output_type -> ums.v1.ServerFrame
	23, // 31: ums.v1.SpinePublish.Publish:output_type -> ums.v1.PublishResponse
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_ums_v1_spine_proto_init() }
func file_proto_ums_v1_spine_proto_init() {
	if File_proto_ums_v1_spine_proto != nil {
		return
	}
	file_proto_ums_v1_spine_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Ack)(nil),
		(*ClientFrame_AckSet)(nil),
		(*ClientFrame_Subscribe)(nil),
		(*ClientFrame_Ping)(nil),
		(*ClientFrame_FlowHint)(nil),
		(*ClientFrame_Nack)(nil),
	}
	file_proto_ums_v1_spine_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerFrame_Welcome)(nil),
		(*ServerFrame_Deliver)(nil),
		(*ServerFrame_SubscribeOk)(nil),
		(*ServerFrame_Pong)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_ResumeOk)(nil),
		(*ServerFrame_ResumeDenied)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ums_v1_spine_proto_rawDesc), len(file_proto_ums_v1_spine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ums_v1_spine_proto_goTypes,
		DependencyIndexes: file_proto_ums_v1_spine_proto_depIdxs,
		EnumInfos:         file_proto_ums_v1_spine_proto_enumTypes,
		MessageInfos:      file_proto_ums_v1_spine_proto_msgTypes,
	}.Build()
	File_proto_ums_v1_spine_proto = out.File
	file_proto_ums_v1_spine_proto_goTypes = nil
	file_proto_ums_v1_spine_proto_depIdxs = nil
}
