// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/ums/v1/spine.proto

package umsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpineStream_Connect_FullMethodName = "/ums.v1.SpineStream/Connect"
)

// SpineStreamClient is the client API for SpineStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpineStream is the primary bidirectional streaming service for UMS
type SpineStreamClient interface {
	// Connect initiates a bidirectional stream for client-server communication
	// Clients send ClientFrame messages, server responds with ServerFrame messages
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type spineStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewSpineStreamClient(cc grpc.ClientConnInterface) SpineStreamClient {
	return &spineStreamClient{cc}
}

func (c *spineStreamClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpineStream_ServiceDesc.Streams[0], SpineStream_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpineStream_ConnectClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// SpineStreamServer is the server API for SpineStream service.
// All implementations must embed UnimplementedSpineStreamServer
// for forward compatibility.
//
// SpineStream is the primary bidirectional streaming service for UMS
type SpineStreamServer interface {
	// Connect initiates a bidirectional stream for client-server communication
	// Clients send ClientFrame messages, server responds with ServerFrame messages
	Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedSpineStreamServer()
}

// UnimplementedSpineStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpineStreamServer struct{}

func (UnimplementedSpineStreamServer) Connect(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSpineStreamServer) mustEmbedUnimplementedSpineStreamServer() {}
func (UnimplementedSpineStreamServer) testEmbeddedByValue()                     {}

// UnsafeSpineStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpineStreamServer will
// result in compilation errors.
type UnsafeSpineStreamServer interface {
	mustEmbedUnimplementedSpineStreamServer()
}

func RegisterSpineStreamServer(s grpc.ServiceRegistrar, srv SpineStreamServer) {
	// If the following call pancis, it indicates UnimplementedSpineStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpineStream_ServiceDesc, srv)
}

func _SpineStream_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpineStreamServer).Connect(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpineStream_ConnectServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// SpineStream_ServiceDesc is the grpc.ServiceDesc for SpineStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpineStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ums.v1.SpineStream",
	HandlerType: (*SpineStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SpineStream_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ums/v1/spine.proto",
}

const (
	SpinePublish_Publish_FullMethodName = "/ums.v1.SpinePublish/Publish"
)

// SpinePublishClient is the client API for SpinePublish service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpinePublish is the service used by server_api/UCRS to publish envelopes
type SpinePublishClient interface {
	// Publish pushes envelopes into target mailboxes
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type spinePublishClient struct {
	cc grpc.ClientConnInterface
}

func NewSpinePublishClient(cc grpc.ClientConnInterface) SpinePublishClient {
	return &spinePublishClient{cc}
}

func (c *spinePublishClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SpinePublish_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpinePublishServer is the server API for SpinePublish service.
// All implementations must embed UnimplementedSpinePublishServer
// for forward compatibility.
//
// SpinePublish is the service used by server_api/UCRS to publish envelopes
type SpinePublishServer interface {
	// Publish pushes envelopes into target mailboxes
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedSpinePublishServer()
}

// UnimplementedSpinePublishServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpinePublishServer struct{}

func (UnimplementedSpinePublishServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedSpinePublishServer) mustEmbedUnimplementedSpinePublishServer() {}
func (UnimplementedSpinePublishServer) testEmbeddedByValue()                      {}

// UnsafeSpinePublishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpinePublishServer will
// result in compilation errors.
type UnsafeSpinePublishServer interface {
	mustEmbedUnimplementedSpinePublishServer()
}

func RegisterSpinePublishServer(s grpc.ServiceRegistrar, srv SpinePublishServer) {
	// If the following call pancis, it indicates UnimplementedSpinePublishServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpinePublish_ServiceDesc, srv)
}

func _SpinePublish_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpinePublishServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpinePublish_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpinePublishServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpinePublish_ServiceDesc is the grpc.ServiceDesc for SpinePublish service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpinePublish_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ums.v1.SpinePublish",
	HandlerType: (*SpinePublishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _SpinePublish_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ums/v1/spine.proto",
}
