// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin/admin_cursors.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCursorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`    // Optional filter
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"` // Optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                         // 0 = default (50)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCursorsRequest) Reset() {
	*x = ListCursorsRequest{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCursorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorsRequest) ProtoMessage() {}

func (x *ListCursorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorsRequest.ProtoReflect.Descriptor instead.
func (*ListCursorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{0}
}

func (x *ListCursorsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListCursorsRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *ListCursorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCursorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCursorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursors       []*CursorSummary       `protobuf:"bytes,1,rep,name=cursors,proto3" json:"cursors,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCursorsResponse) Reset() {
	*x = ListCursorsResponse{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCursorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCursorsResponse) ProtoMessage() {}

func (x *ListCursorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCursorsResponse.ProtoReflect.Descriptor instead.
func (*ListCursorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{1}
}

func (x *ListCursorsResponse) GetCursors() []*CursorSummary {
	if x != nil {
		return x.Cursors
	}
	return nil
}

func (x *ListCursorsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CursorSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	LastAckedSeq  uint64                 `protobuf:"varint,3,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorSummary) Reset() {
	*x = CursorSummary{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorSummary) ProtoMessage() {}

func (x *CursorSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorSummary.ProtoReflect.Descriptor instead.
func (*CursorSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{2}
}

func (x *CursorSummary) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CursorSummary) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *CursorSummary) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

func (x *CursorSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCursorRequest) Reset() {
	*x = GetCursorRequest{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCursorRequest) ProtoMessage() {}

func (x *GetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCursorRequest.ProtoReflect.Descriptor instead.
func (*GetCursorRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{3}
}

func (x *GetCursorRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *GetCursorRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

type CursorDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MailboxId      string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	LastAckedSeq   uint64                 `protobuf:"varint,3,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	MailboxNextSeq uint64                 `protobuf:"varint,4,opt,name=mailbox_next_seq,json=mailboxNextSeq,proto3" json:"mailbox_next_seq,omitempty"` // From mailbox — used to compute inflight
	InflightCount  uint64                 `protobuf:"varint,5,opt,name=inflight_count,json=inflightCount,proto3" json:"inflight_count,omitempty"`      // mailbox_next_seq - last_acked_seq (approx)
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CursorDetail) Reset() {
	*x = CursorDetail{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorDetail) ProtoMessage() {}

func (x *CursorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorDetail.ProtoReflect.Descriptor instead.
func (*CursorDetail) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{4}
}

func (x *CursorDetail) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CursorDetail) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *CursorDetail) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

func (x *CursorDetail) GetMailboxNextSeq() uint64 {
	if x != nil {
		return x.MailboxNextSeq
	}
	return 0
}

func (x *CursorDetail) GetInflightCount() uint64 {
	if x != nil {
		return x.InflightCount
	}
	return 0
}

func (x *CursorDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MailboxId     string                 `protobuf:"bytes,2,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // Reset last_acked_seq to this value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCursorRequest) Reset() {
	*x = ResetCursorRequest{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCursorRequest) ProtoMessage() {}

func (x *ResetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCursorRequest.ProtoReflect.Descriptor instead.
func (*ResetCursorRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{5}
}

func (x *ResetCursorRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ResetCursorRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *ResetCursorRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteServerCursorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerCursorsRequest) Reset() {
	*x = DeleteServerCursorsRequest{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerCursorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerCursorsRequest) ProtoMessage() {}

func (x *DeleteServerCursorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerCursorsRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerCursorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteServerCursorsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DeleteServerCursorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerCursorsResponse) Reset() {
	*x = DeleteServerCursorsResponse{}
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerCursorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerCursorsResponse) ProtoMessage() {}

func (x *DeleteServerCursorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_cursors_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerCursorsResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerCursorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_cursors_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteServerCursorsResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_proto_admin_admin_cursors_proto protoreflect.FileDescriptor

const file_proto_admin_admin_cursors_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/admin/admin_cursors.proto\x12\n" +
	"spineadmin\x1a\x18proto/admin/common.proto\"~\n" +
	"\x12ListCursorsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x82\x01\n" +
	"\x13ListCursorsResponse\x123\n" +
	"\acursors\x18\x01 \x03(\v2\x19.spineadmin.CursorSummaryR\acursors\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.spineadmin.PaginationR\n" +
	"pagination\"\x90\x01\n" +
	"\rCursorSummary\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12$\n" +
	"\x0elast_acked_seq\x18\x03 \x01(\x04R\flastAckedSeq\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"N\n" +
	"\x10GetCursorRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\"\xe0\x01\n" +
	"\fCursorDetail\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12$\n" +
	"\x0elast_acked_seq\x18\x03 \x01(\x04R\flastAckedSeq\x12(\n" +
	"\x10mailbox_next_seq\x18\x04 \x01(\x04R\x0emailboxNextSeq\x12%\n" +
	"\x0einflight_count\x18\x05 \x01(\x04R\rinflightCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"b\n" +
	"\x12ResetCursorRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x02 \x01(\tR\tmailboxId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"9\n" +
	"\x1aDeleteServerCursorsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"B\n" +
	"\x1bDeleteServerCursorsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount2\xc9\x02\n" +
	"\x13AdminCursorsService\x12I\n" +
	"\x04List\x12\x1e.spineadmin.ListCursorsRequest\x1a\x1f.spineadmin.ListCursorsResponse\"\x00\x12?\n" +
	"\x03Get\x12\x1c.spineadmin.GetCursorRequest\x1a\x18.spineadmin.CursorDetail\"\x00\x12<\n" +
	"\x05Reset\x12\x1e.spineadmin.ResetCursorRequest\x1a\x11.spineadmin.Empty\"\x00\x12h\n" +
	"\x13DeleteServerCursors\x12&.spineadmin.DeleteServerCursorsRequest\x1a'.spineadmin.DeleteServerCursorsResponse\"\x00BBZ@github.com/ambientlabscomputing/mycelium_spine/proto/admin;adminb\x06proto3"

var (
	file_proto_admin_admin_cursors_proto_rawDescOnce sync.Once
	file_proto_admin_admin_cursors_proto_rawDescData []byte
)

func file_proto_admin_admin_cursors_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_cursors_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_cursors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_cursors_proto_rawDesc), len(file_proto_admin_admin_cursors_proto_rawDesc)))
	})
	return file_proto_admin_admin_cursors_proto_rawDescData
}

var file_proto_admin_admin_cursors_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_admin_admin_cursors_proto_goTypes = []any{
	(*ListCursorsRequest)(nil),          // 0: spineadmin.ListCursorsRequest
	(*ListCursorsResponse)(nil),         // 1: spineadmin.ListCursorsResponse
	(*CursorSummary)(nil),               // 2: spineadmin.CursorSummary
	(*GetCursorRequest)(nil),            // 3: spineadmin.GetCursorRequest
	(*CursorDetail)(nil),                // 4: spineadmin.CursorDetail
	(*ResetCursorRequest)(nil),          // 5: spineadmin.ResetCursorRequest
	(*DeleteServerCursorsRequest)(nil),  // 6: spineadmin.DeleteServerCursorsRequest
	(*DeleteServerCursorsResponse)(nil), // 7: spineadmin.DeleteServerCursorsResponse
	(*Pagination)(nil),                  // 8: spineadmin.Pagination
	(*Empty)(nil),                       // 9: spineadmin.Empty
}
var file_proto_admin_admin_cursors_proto_depIdxs = []int32{
	2, // 0: spineadmin.ListCursorsResponse.cursors:type_name -> spineadmin.CursorSummary
	8, // 1: spineadmin.ListCursorsResponse.pagination:type_name -> spineadmin.Pagination
	0, // 2: spineadmin.AdminCursorsService.List:input_type -> spineadmin.ListCursorsRequest
	3, // 3: spineadmin.AdminCursorsService.Get:input_type -> spineadmin.GetCursorRequest
	5, // 4: spineadmin.AdminCursorsService.Reset:input_type -> spineadmin.ResetCursorRequest
	6, // 5: spineadmin.AdminCursorsService.DeleteServerCursors:input_type -> spineadmin.DeleteServerCursorsRequest
	1, // 6: spineadmin.AdminCursorsService.List:output_type -> spineadmin.ListCursorsResponse
	4, // 7: spineadmin.AdminCursorsService.Get:output_type -> spineadmin.CursorDetail
	9, // 8: spineadmin.AdminCursorsService.Reset:output_type -> spineadmin.Empty
	7, // 9: spineadmin.AdminCursorsService.DeleteServerCursors:output_type -> spineadmin.DeleteServerCursorsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_cursors_proto_init() }
func file_proto_admin_admin_cursors_proto_init() {
	if File_proto_admin_admin_cursors_proto != nil {
		return
	}
	file_proto_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_cursors_proto_rawDesc), len(file_proto_admin_admin_cursors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_cursors_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_cursors_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_cursors_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_cursors_proto = out.File
	file_proto_admin_admin_cursors_proto_goTypes = nil
	file_proto_admin_admin_cursors_proto_depIdxs = nil
}
