// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin/admin_sessions.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminSessionsService_List_FullMethodName       = "/spineadmin.AdminSessionsService/List"
	AdminSessionsService_Get_FullMethodName        = "/spineadmin.AdminSessionsService/Get"
	AdminSessionsService_Disconnect_FullMethodName = "/spineadmin.AdminSessionsService/Disconnect"
	AdminSessionsService_EvictStale_FullMethodName = "/spineadmin.AdminSessionsService/EvictStale"
)

// AdminSessionsServiceClient is the client API for AdminSessionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminSessionsServiceClient interface {
	List(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	Get(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionDetail, error)
	Disconnect(ctx context.Context, in *DisconnectSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	EvictStale(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EvictStaleResponse, error)
}

type adminSessionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminSessionsServiceClient(cc grpc.ClientConnInterface) AdminSessionsServiceClient {
	return &adminSessionsServiceClient{cc}
}

func (c *adminSessionsServiceClient) List(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AdminSessionsService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSessionsServiceClient) Get(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionDetail)
	err := c.cc.Invoke(ctx, AdminSessionsService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSessionsServiceClient) Disconnect(ctx context.Context, in *DisconnectSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminSessionsService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSessionsServiceClient) EvictStale(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EvictStaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictStaleResponse)
	err := c.cc.Invoke(ctx, AdminSessionsService_EvictStale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminSessionsServiceServer is the server API for AdminSessionsService service.
// All implementations must embed UnimplementedAdminSessionsServiceServer
// for forward compatibility.
type AdminSessionsServiceServer interface {
	List(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	Get(context.Context, *GetSessionRequest) (*SessionDetail, error)
	Disconnect(context.Context, *DisconnectSessionRequest) (*Empty, error)
	EvictStale(context.Context, *Empty) (*EvictStaleResponse, error)
	mustEmbedUnimplementedAdminSessionsServiceServer()
}

// UnimplementedAdminSessionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminSessionsServiceServer struct{}

func (UnimplementedAdminSessionsServiceServer) List(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminSessionsServiceServer) Get(context.Context, *GetSessionRequest) (*SessionDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAdminSessionsServiceServer) Disconnect(context.Context, *DisconnectSessionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedAdminSessionsServiceServer) EvictStale(context.Context, *Empty) (*EvictStaleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvictStale not implemented")
}
func (UnimplementedAdminSessionsServiceServer) mustEmbedUnimplementedAdminSessionsServiceServer() {}
func (UnimplementedAdminSessionsServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdminSessionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminSessionsServiceServer will
// result in compilation errors.
type UnsafeAdminSessionsServiceServer interface {
	mustEmbedUnimplementedAdminSessionsServiceServer()
}

func RegisterAdminSessionsServiceServer(s grpc.ServiceRegistrar, srv AdminSessionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminSessionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminSessionsService_ServiceDesc, srv)
}

func _AdminSessionsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSessionsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSessionsService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSessionsServiceServer).List(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSessionsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSessionsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSessionsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSessionsServiceServer).Get(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSessionsService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSessionsServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSessionsService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSessionsServiceServer).Disconnect(ctx, req.(*DisconnectSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSessionsService_EvictStale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSessionsServiceServer).EvictStale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminSessionsService_EvictStale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSessionsServiceServer).EvictStale(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminSessionsService_ServiceDesc is the grpc.ServiceDesc for AdminSessionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminSessionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spineadmin.AdminSessionsService",
	HandlerType: (*AdminSessionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AdminSessionsService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AdminSessionsService_Get_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _AdminSessionsService_Disconnect_Handler,
		},
		{
			MethodName: "EvictStale",
			Handler:    _AdminSessionsService_EvictStale_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin_sessions.proto",
}
