// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin/admin_cursors.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminCursorsService_List_FullMethodName                = "/spineadmin.AdminCursorsService/List"
	AdminCursorsService_Get_FullMethodName                 = "/spineadmin.AdminCursorsService/Get"
	AdminCursorsService_Reset_FullMethodName               = "/spineadmin.AdminCursorsService/Reset"
	AdminCursorsService_DeleteServerCursors_FullMethodName = "/spineadmin.AdminCursorsService/DeleteServerCursors"
)

// AdminCursorsServiceClient is the client API for AdminCursorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminCursorsServiceClient interface {
	List(ctx context.Context, in *ListCursorsRequest, opts ...grpc.CallOption) (*ListCursorsResponse, error)
	Get(ctx context.Context, in *GetCursorRequest, opts ...grpc.CallOption) (*CursorDetail, error)
	Reset(ctx context.Context, in *ResetCursorRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteServerCursors(ctx context.Context, in *DeleteServerCursorsRequest, opts ...grpc.CallOption) (*DeleteServerCursorsResponse, error)
}

type adminCursorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminCursorsServiceClient(cc grpc.ClientConnInterface) AdminCursorsServiceClient {
	return &adminCursorsServiceClient{cc}
}

func (c *adminCursorsServiceClient) List(ctx context.Context, in *ListCursorsRequest, opts ...grpc.CallOption) (*ListCursorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCursorsResponse)
	err := c.cc.Invoke(ctx, AdminCursorsService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCursorsServiceClient) Get(ctx context.Context, in *GetCursorRequest, opts ...grpc.CallOption) (*CursorDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CursorDetail)
	err := c.cc.Invoke(ctx, AdminCursorsService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCursorsServiceClient) Reset(ctx context.Context, in *ResetCursorRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AdminCursorsService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCursorsServiceClient) DeleteServerCursors(ctx context.Context, in *DeleteServerCursorsRequest, opts ...grpc.CallOption) (*DeleteServerCursorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServerCursorsResponse)
	err := c.cc.Invoke(ctx, AdminCursorsService_DeleteServerCursors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminCursorsServiceServer is the server API for AdminCursorsService service.
// All implementations must embed UnimplementedAdminCursorsServiceServer
// for forward compatibility.
type AdminCursorsServiceServer interface {
	List(context.Context, *ListCursorsRequest) (*ListCursorsResponse, error)
	Get(context.Context, *GetCursorRequest) (*CursorDetail, error)
	Reset(context.Context, *ResetCursorRequest) (*Empty, error)
	DeleteServerCursors(context.Context, *DeleteServerCursorsRequest) (*DeleteServerCursorsResponse, error)
	mustEmbedUnimplementedAdminCursorsServiceServer()
}

// UnimplementedAdminCursorsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminCursorsServiceServer struct{}

func (UnimplementedAdminCursorsServiceServer) List(context.Context, *ListCursorsRequest) (*ListCursorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminCursorsServiceServer) Get(context.Context, *GetCursorRequest) (*CursorDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAdminCursorsServiceServer) Reset(context.Context, *ResetCursorRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedAdminCursorsServiceServer) DeleteServerCursors(context.Context, *DeleteServerCursorsRequest) (*DeleteServerCursorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteServerCursors not implemented")
}
func (UnimplementedAdminCursorsServiceServer) mustEmbedUnimplementedAdminCursorsServiceServer() {}
func (UnimplementedAdminCursorsServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminCursorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminCursorsServiceServer will
// result in compilation errors.
type UnsafeAdminCursorsServiceServer interface {
	mustEmbedUnimplementedAdminCursorsServiceServer()
}

func RegisterAdminCursorsServiceServer(s grpc.ServiceRegistrar, srv AdminCursorsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminCursorsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminCursorsService_ServiceDesc, srv)
}

func _AdminCursorsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCursorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCursorsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCursorsService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCursorsServiceServer).List(ctx, req.(*ListCursorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCursorsService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCursorsServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCursorsService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCursorsServiceServer).Get(ctx, req.(*GetCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCursorsService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCursorsServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCursorsService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCursorsServiceServer).Reset(ctx, req.(*ResetCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCursorsService_DeleteServerCursors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServerCursorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCursorsServiceServer).DeleteServerCursors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCursorsService_DeleteServerCursors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCursorsServiceServer).DeleteServerCursors(ctx, req.(*DeleteServerCursorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminCursorsService_ServiceDesc is the grpc.ServiceDesc for AdminCursorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminCursorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spineadmin.AdminCursorsService",
	HandlerType: (*AdminCursorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AdminCursorsService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AdminCursorsService_Get_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _AdminCursorsService_Reset_Handler,
		},
		{
			MethodName: "DeleteServerCursors",
			Handler:    _AdminCursorsService_DeleteServerCursors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin_cursors.proto",
}
