// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin/admin_mailboxes.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMailboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                // Optional filter
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // Optional filter: SERVER, CLUSTER, ORG, SERVICE, BROADCAST
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // 0 = default (50)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMailboxesRequest) Reset() {
	*x = ListMailboxesRequest{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMailboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMailboxesRequest) ProtoMessage() {}

func (x *ListMailboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMailboxesRequest.ProtoReflect.Descriptor instead.
func (*ListMailboxesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{0}
}

func (x *ListMailboxesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListMailboxesRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *ListMailboxesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMailboxesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMailboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mailboxes     []*MailboxSummary      `protobuf:"bytes,1,rep,name=mailboxes,proto3" json:"mailboxes,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMailboxesResponse) Reset() {
	*x = ListMailboxesResponse{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMailboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMailboxesResponse) ProtoMessage() {}

func (x *ListMailboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMailboxesResponse.ProtoReflect.Descriptor instead.
func (*ListMailboxesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{1}
}

func (x *ListMailboxesResponse) GetMailboxes() []*MailboxSummary {
	if x != nil {
		return x.Mailboxes
	}
	return nil
}

func (x *ListMailboxesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MailboxSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	NextSeq       uint64                 `protobuf:"varint,5,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailboxSummary) Reset() {
	*x = MailboxSummary{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxSummary) ProtoMessage() {}

func (x *MailboxSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxSummary.ProtoReflect.Descriptor instead.
func (*MailboxSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{2}
}

func (x *MailboxSummary) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *MailboxSummary) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *MailboxSummary) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MailboxSummary) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *MailboxSummary) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *MailboxSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MailboxSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMailboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMailboxRequest) Reset() {
	*x = GetMailboxRequest{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMailboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailboxRequest) ProtoMessage() {}

func (x *GetMailboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailboxRequest.ProtoReflect.Descriptor instead.
func (*GetMailboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{3}
}

func (x *GetMailboxRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

type MailboxDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MailboxId        string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	TargetType       string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId         string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	NextSeq          uint64                 `protobuf:"varint,5,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RetentionSeconds int32                  `protobuf:"varint,8,opt,name=retention_seconds,json=retentionSeconds,proto3" json:"retention_seconds,omitempty"`
	MaxEnvelopes     int32                  `protobuf:"varint,9,opt,name=max_envelopes,json=maxEnvelopes,proto3" json:"max_envelopes,omitempty"`
	MaxBytes         int32                  `protobuf:"varint,10,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MailboxDetail) Reset() {
	*x = MailboxDetail{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailboxDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxDetail) ProtoMessage() {}

func (x *MailboxDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxDetail.ProtoReflect.Descriptor instead.
func (*MailboxDetail) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{4}
}

func (x *MailboxDetail) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *MailboxDetail) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *MailboxDetail) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MailboxDetail) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *MailboxDetail) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *MailboxDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MailboxDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MailboxDetail) GetRetentionSeconds() int32 {
	if x != nil {
		return x.RetentionSeconds
	}
	return 0
}

func (x *MailboxDetail) GetMaxEnvelopes() int32 {
	if x != nil {
		return x.MaxEnvelopes
	}
	return 0
}

func (x *MailboxDetail) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type ListEnvelopesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // Start at this sequence (inclusive); 0 = beginning
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                    // 0 = default (20)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvelopesRequest) Reset() {
	*x = ListEnvelopesRequest{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvelopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvelopesRequest) ProtoMessage() {}

func (x *ListEnvelopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvelopesRequest.ProtoReflect.Descriptor instead.
func (*ListEnvelopesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{5}
}

func (x *ListEnvelopesRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *ListEnvelopesRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *ListEnvelopesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EnvelopeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Qos           string                 `protobuf:"bytes,4,opt,name=qos,proto3" json:"qos,omitempty"`
	OrgId         string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RequiresAck   bool                   `protobuf:"varint,6,opt,name=requires_ack,json=requiresAck,proto3" json:"requires_ack,omitempty"`
	ExpiresAtMs   int64                  `protobuf:"varint,7,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeSummary) Reset() {
	*x = EnvelopeSummary{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeSummary) ProtoMessage() {}

func (x *EnvelopeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeSummary.ProtoReflect.Descriptor instead.
func (*EnvelopeSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{6}
}

func (x *EnvelopeSummary) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

func (x *EnvelopeSummary) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EnvelopeSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnvelopeSummary) GetQos() string {
	if x != nil {
		return x.Qos
	}
	return ""
}

func (x *EnvelopeSummary) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *EnvelopeSummary) GetRequiresAck() bool {
	if x != nil {
		return x.RequiresAck
	}
	return false
}

func (x *EnvelopeSummary) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type ListEnvelopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*EnvelopeSummary     `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvelopesResponse) Reset() {
	*x = ListEnvelopesResponse{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvelopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvelopesResponse) ProtoMessage() {}

func (x *ListEnvelopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvelopesResponse.ProtoReflect.Descriptor instead.
func (*ListEnvelopesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{7}
}

func (x *ListEnvelopesResponse) GetEnvelopes() []*EnvelopeSummary {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

type PurgeExpiredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeExpiredRequest) Reset() {
	*x = PurgeExpiredRequest{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeExpiredRequest) ProtoMessage() {}

func (x *PurgeExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeExpiredRequest.ProtoReflect.Descriptor instead.
func (*PurgeExpiredRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{8}
}

func (x *PurgeExpiredRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

type PurgeExpiredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeExpiredResponse) Reset() {
	*x = PurgeExpiredResponse{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeExpiredResponse) ProtoMessage() {}

func (x *PurgeExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeExpiredResponse.ProtoReflect.Descriptor instead.
func (*PurgeExpiredResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{9}
}

func (x *PurgeExpiredResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ClearOutboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     string                 `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearOutboxRequest) Reset() {
	*x = ClearOutboxRequest{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearOutboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearOutboxRequest) ProtoMessage() {}

func (x *ClearOutboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearOutboxRequest.ProtoReflect.Descriptor instead.
func (*ClearOutboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{10}
}

func (x *ClearOutboxRequest) GetMailboxId() string {
	if x != nil {
		return x.MailboxId
	}
	return ""
}

type ClearOutboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearOutboxResponse) Reset() {
	*x = ClearOutboxResponse{}
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearOutboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearOutboxResponse) ProtoMessage() {}

func (x *ClearOutboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_mailboxes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearOutboxResponse.ProtoReflect.Descriptor instead.
func (*ClearOutboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_mailboxes_proto_rawDescGZIP(), []int{11}
}

func (x *ClearOutboxResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_proto_admin_admin_mailboxes_proto protoreflect.FileDescriptor

const file_proto_admin_admin_mailboxes_proto_rawDesc = "" +
	"\n" +
	"!proto/admin/admin_mailboxes.proto\x12\n" +
	"spineadmin\x1a\x18proto/admin/common.proto\"|\n" +
	"\x14ListMailboxesRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\x89\x01\n" +
	"\x15ListMailboxesResponse\x128\n" +
	"\tmailboxes\x18\x01 \x03(\v2\x1a.spineadmin.MailboxSummaryR\tmailboxes\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.spineadmin.PaginationR\n" +
	"pagination\"\xdd\x01\n" +
	"\x0eMailboxSummary\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x19\n" +
	"\bnext_seq\x18\x05 \x01(\x04R\anextSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"2\n" +
	"\x11GetMailboxRequest\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\"\xcb\x02\n" +
	"\rMailboxDetail\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x19\n" +
	"\bnext_seq\x18\x05 \x01(\x04R\anextSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12+\n" +
	"\x11retention_seconds\x18\b \x01(\x05R\x10retentionSeconds\x12#\n" +
	"\rmax_envelopes\x18\t \x01(\x05R\fmaxEnvelopes\x12\x1b\n" +
	"\tmax_bytes\x18\n" +
	" \x01(\x05R\bmaxBytes\"f\n" +
	"\x14ListEnvelopesRequest\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc6\x01\n" +
	"\x0fEnvelopeSummary\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03qos\x18\x04 \x01(\tR\x03qos\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12!\n" +
	"\frequires_ack\x18\x06 \x01(\bR\vrequiresAck\x12\"\n" +
	"\rexpires_at_ms\x18\a \x01(\x03R\vexpiresAtMs\"R\n" +
	"\x15ListEnvelopesResponse\x129\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x1b.spineadmin.EnvelopeSummaryR\tenvelopes\"4\n" +
	"\x13PurgeExpiredRequest\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\";\n" +
	"\x14PurgeExpiredResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount\"3\n" +
	"\x12ClearOutboxRequest\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\tR\tmailboxId\":\n" +
	"\x13ClearOutboxResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount2\xa8\x03\n" +
	"\x15AdminMailboxesService\x12M\n" +
	"\x04List\x12 .spineadmin.ListMailboxesRequest\x1a!.spineadmin.ListMailboxesResponse\"\x00\x12A\n" +
	"\x03Get\x12\x1d.spineadmin.GetMailboxRequest\x1a\x19.spineadmin.MailboxDetail\"\x00\x12V\n" +
	"\rListEnvelopes\x12 .spineadmin.ListEnvelopesRequest\x1a!.spineadmin.ListEnvelopesResponse\"\x00\x12S\n" +
	"\fPurgeExpired\x12\x1f.spineadmin.PurgeExpiredRequest\x1a .spineadmin.PurgeExpiredResponse\"\x00\x12P\n" +
	"\vClearOutbox\x12\x1e.spineadmin.ClearOutboxRequest\x1a\x1f.spineadmin.ClearOutboxResponse\"\x00BBZ@github.com/ambientlabscomputing/mycelium_spine/proto/admin;adminb\x06proto3"

var (
	file_proto_admin_admin_mailboxes_proto_rawDescOnce sync.Once
	file_proto_admin_admin_mailboxes_proto_rawDescData []byte
)

func file_proto_admin_admin_mailboxes_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_mailboxes_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_mailboxes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_mailboxes_proto_rawDesc), len(file_proto_admin_admin_mailboxes_proto_rawDesc)))
	})
	return file_proto_admin_admin_mailboxes_proto_rawDescData
}

var file_proto_admin_admin_mailboxes_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_admin_admin_mailboxes_proto_goTypes = []any{
	(*ListMailboxesRequest)(nil),  // 0: spineadmin.ListMailboxesRequest
	(*ListMailboxesResponse)(nil), // 1: spineadmin.ListMailboxesResponse
	(*MailboxSummary)(nil),        // 2: spineadmin.MailboxSummary
	(*GetMailboxRequest)(nil),     // 3: spineadmin.GetMailboxRequest
	(*MailboxDetail)(nil),         // 4: spineadmin.MailboxDetail
	(*ListEnvelopesRequest)(nil),  // 5: spineadmin.ListEnvelopesRequest
	(*EnvelopeSummary)(nil),       // 6: spineadmin.EnvelopeSummary
	(*ListEnvelopesResponse)(nil), // 7: spineadmin.ListEnvelopesResponse
	(*PurgeExpiredRequest)(nil),   // 8: spineadmin.PurgeExpiredRequest
	(*PurgeExpiredResponse)(nil),  // 9: spineadmin.PurgeExpiredResponse
	(*ClearOutboxRequest)(nil),    // 10: spineadmin.ClearOutboxRequest
	(*ClearOutboxResponse)(nil),   // 11: spineadmin.ClearOutboxResponse
	(*Pagination)(nil),            // 12: spineadmin.Pagination
}
var file_proto_admin_admin_mailboxes_proto_depIdxs = []int32{
	2,  // 0: spineadmin.ListMailboxesResponse.mailboxes:type_name -> spineadmin.MailboxSummary
	12, // 1: spineadmin.ListMailboxesResponse.pagination:type_name -> spineadmin.Pagination
	6,  // 2: spineadmin.ListEnvelopesResponse.envelopes:type_name -> spineadmin.EnvelopeSummary
	0,  // 3: spineadmin.AdminMailboxesService.List:input_type -> spineadmin.ListMailboxesRequest
	3,  // 4: spineadmin.AdminMailboxesService.Get:input_type -> spineadmin.GetMailboxRequest
	5,  // 5: spineadmin.AdminMailboxesService.ListEnvelopes:input_type -> spineadmin.ListEnvelopesRequest
	8,  // 6: spineadmin.AdminMailboxesService.PurgeExpired:input_type -> spineadmin.PurgeExpiredRequest
	10, // 7: spineadmin.AdminMailboxesService.ClearOutbox:input_type -> spineadmin.ClearOutboxRequest
	1,  // 8: spineadmin.AdminMailboxesService.List:output_type -> spineadmin.ListMailboxesResponse
	4,  // 9: spineadmin.AdminMailboxesService.Get:output_type -> spineadmin.MailboxDetail
	7,  // 10: spineadmin.AdminMailboxesService.ListEnvelopes:output_type -> spineadmin.ListEnvelopesResponse
	9,  // 11: spineadmin.AdminMailboxesService.PurgeExpired:output_type -> spineadmin.PurgeExpiredResponse
	11, // 12: spineadmin.AdminMailboxesService.ClearOutbox:output_type -> spineadmin.ClearOutboxResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_mailboxes_proto_init() }
func file_proto_admin_admin_mailboxes_proto_init() {
	if File_proto_admin_admin_mailboxes_proto != nil {
		return
	}
	file_proto_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_mailboxes_proto_rawDesc), len(file_proto_admin_admin_mailboxes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_mailboxes_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_mailboxes_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_mailboxes_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_mailboxes_proto = out.File
	file_proto_admin_admin_mailboxes_proto_goTypes = nil
	file_proto_admin_admin_mailboxes_proto_depIdxs = nil
}
