// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin/admin_workers.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminWorkersService_GetStats_FullMethodName = "/spineadmin.AdminWorkersService/GetStats"
)

// AdminWorkersServiceClient is the client API for AdminWorkersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminWorkersServiceClient interface {
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkerStatsResponse, error)
}

type adminWorkersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminWorkersServiceClient(cc grpc.ClientConnInterface) AdminWorkersServiceClient {
	return &adminWorkersServiceClient{cc}
}

func (c *adminWorkersServiceClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WorkerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerStatsResponse)
	err := c.cc.Invoke(ctx, AdminWorkersService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminWorkersServiceServer is the server API for AdminWorkersService service.
// All implementations must embed UnimplementedAdminWorkersServiceServer
// for forward compatibility.
type AdminWorkersServiceServer interface {
	GetStats(context.Context, *Empty) (*WorkerStatsResponse, error)
	mustEmbedUnimplementedAdminWorkersServiceServer()
}

// UnimplementedAdminWorkersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminWorkersServiceServer struct{}

func (UnimplementedAdminWorkersServiceServer) GetStats(context.Context, *Empty) (*WorkerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAdminWorkersServiceServer) mustEmbedUnimplementedAdminWorkersServiceServer() {}
func (UnimplementedAdminWorkersServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminWorkersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminWorkersServiceServer will
// result in compilation errors.
type UnsafeAdminWorkersServiceServer interface {
	mustEmbedUnimplementedAdminWorkersServiceServer()
}

func RegisterAdminWorkersServiceServer(s grpc.ServiceRegistrar, srv AdminWorkersServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminWorkersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminWorkersService_ServiceDesc, srv)
}

func _AdminWorkersService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminWorkersServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminWorkersService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminWorkersServiceServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminWorkersService_ServiceDesc is the grpc.ServiceDesc for AdminWorkersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminWorkersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spineadmin.AdminWorkersService",
	HandlerType: (*AdminWorkersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _AdminWorkersService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin_workers.proto",
}
