// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin/admin_workers.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Worker pool stats keyed by pool name (session, delivery, ack, mailbox).
	Pools         map[string]*PoolStats `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatsResponse) Reset() {
	*x = WorkerStatsResponse{}
	mi := &file_proto_admin_admin_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatsResponse) ProtoMessage() {}

func (x *WorkerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatsResponse.ProtoReflect.Descriptor instead.
func (*WorkerStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_workers_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerStatsResponse) GetPools() map[string]*PoolStats {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkers  int32                  `protobuf:"varint,1,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueueDepth     int32                  `protobuf:"varint,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	QueueCapacity  int32                  `protobuf:"varint,3,opt,name=queue_capacity,json=queueCapacity,proto3" json:"queue_capacity,omitempty"`
	TasksProcessed int64                  `protobuf:"varint,4,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	TaskErrors     int64                  `protobuf:"varint,5,opt,name=task_errors,json=taskErrors,proto3" json:"task_errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolStats) Reset() {
	*x = PoolStats{}
	mi := &file_proto_admin_admin_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStats) ProtoMessage() {}

func (x *PoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStats.ProtoReflect.Descriptor instead.
func (*PoolStats) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_workers_proto_rawDescGZIP(), []int{1}
}

func (x *PoolStats) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *PoolStats) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *PoolStats) GetQueueCapacity() int32 {
	if x != nil {
		return x.QueueCapacity
	}
	return 0
}

func (x *PoolStats) GetTasksProcessed() int64 {
	if x != nil {
		return x.TasksProcessed
	}
	return 0
}

func (x *PoolStats) GetTaskErrors() int64 {
	if x != nil {
		return x.TaskErrors
	}
	return 0
}

var File_proto_admin_admin_workers_proto protoreflect.FileDescriptor

const file_proto_admin_admin_workers_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/admin/admin_workers.proto\x12\n" +
	"spineadmin\x1a\x18proto/admin/common.proto\"\xa8\x01\n" +
	"\x13WorkerStatsResponse\x12@\n" +
	"\x05pools\x18\x01 \x03(\v2*.spineadmin.WorkerStatsResponse.PoolsEntryR\x05pools\x1aO\n" +
	"\n" +
	"PoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.spineadmin.PoolStatsR\x05value:\x028\x01\"\xc4\x01\n" +
	"\tPoolStats\x12%\n" +
	"\x0eactive_workers\x18\x01 \x01(\x05R\ractiveWorkers\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\x05R\n" +
	"queueDepth\x12%\n" +
	"\x0equeue_capacity\x18\x03 \x01(\x05R\rqueueCapacity\x12'\n" +
	"\x0ftasks_processed\x18\x04 \x01(\x03R\x0etasksProcessed\x12\x1f\n" +
	"\vtask_errors\x18\x05 \x01(\x03R\n" +
	"taskErrors2W\n" +
	"\x13AdminWorkersService\x12@\n" +
	"\bGetStats\x12\x11.spineadmin.Empty\x1a\x1f.spineadmin.WorkerStatsResponse\"\x00BBZ@github.com/ambientlabscomputing/mycelium_spine/proto/admin;adminb\x06proto3"

var (
	file_proto_admin_admin_workers_proto_rawDescOnce sync.Once
	file_proto_admin_admin_workers_proto_rawDescData []byte
)

func file_proto_admin_admin_workers_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_workers_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_workers_proto_rawDesc), len(file_proto_admin_admin_workers_proto_rawDesc)))
	})
	return file_proto_admin_admin_workers_proto_rawDescData
}

var file_proto_admin_admin_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_admin_admin_workers_proto_goTypes = []any{
	(*WorkerStatsResponse)(nil), // 0: spineadmin.WorkerStatsResponse
	(*PoolStats)(nil),           // 1: spineadmin.PoolStats
	nil,                         // 2: spineadmin.WorkerStatsResponse.PoolsEntry
	(*Empty)(nil),               // 3: spineadmin.Empty
}
var file_proto_admin_admin_workers_proto_depIdxs = []int32{
	2, // 0: spineadmin.WorkerStatsResponse.pools:type_name -> spineadmin.WorkerStatsResponse.PoolsEntry
	1, // 1: spineadmin.WorkerStatsResponse.PoolsEntry.value:type_name -> spineadmin.PoolStats
	3, // 2: spineadmin.AdminWorkersService.GetStats:input_type -> spineadmin.Empty
	0, // 3: spineadmin.AdminWorkersService.GetStats:output_type -> spineadmin.WorkerStatsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_workers_proto_init() }
func file_proto_admin_admin_workers_proto_init() {
	if File_proto_admin_admin_workers_proto != nil {
		return
	}
	file_proto_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_workers_proto_rawDesc), len(file_proto_admin_admin_workers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_workers_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_workers_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_workers_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_workers_proto = out.File
	file_proto_admin_admin_workers_proto_goTypes = nil
	file_proto_admin_admin_workers_proto_depIdxs = nil
}
