// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin/admin_health.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	TotalMailboxes int64                  `protobuf:"varint,3,opt,name=total_mailboxes,json=totalMailboxes,proto3" json:"total_mailboxes,omitempty"`
	Uptime         string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_admin_admin_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalMailboxes() int64 {
	if x != nil {
		return x.TotalMailboxes
	}
	return 0
}

func (x *HealthCheckResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	TotalMailboxes int64                  `protobuf:"varint,3,opt,name=total_mailboxes,json=totalMailboxes,proto3" json:"total_mailboxes,omitempty"`
	Uptime         string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Worker pool stats keyed by pool name.
	WorkerPools map[string]*WorkerPoolStats `protobuf:"bytes,6,rep,name=worker_pools,json=workerPools,proto3" json:"worker_pools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Flow control policy summary.
	FlowControl   *FlowControlConfig `protobuf:"bytes,7,opt,name=flow_control,json=flowControl,proto3" json:"flow_control,omitempty"`
	TlsEnabled    bool               `protobuf:"varint,8,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	MtlsMode      string             `protobuf:"bytes,9,opt,name=mtls_mode,json=mtlsMode,proto3" json:"mtls_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthDetailResponse) Reset() {
	*x = HealthDetailResponse{}
	mi := &file_proto_admin_admin_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDetailResponse) ProtoMessage() {}

func (x *HealthDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDetailResponse.ProtoReflect.Descriptor instead.
func (*HealthDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthDetailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthDetailResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthDetailResponse) GetTotalMailboxes() int64 {
	if x != nil {
		return x.TotalMailboxes
	}
	return 0
}

func (x *HealthDetailResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthDetailResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthDetailResponse) GetWorkerPools() map[string]*WorkerPoolStats {
	if x != nil {
		return x.WorkerPools
	}
	return nil
}

func (x *HealthDetailResponse) GetFlowControl() *FlowControlConfig {
	if x != nil {
		return x.FlowControl
	}
	return nil
}

func (x *HealthDetailResponse) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

func (x *HealthDetailResponse) GetMtlsMode() string {
	if x != nil {
		return x.MtlsMode
	}
	return ""
}

type WorkerPoolStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkers  int32                  `protobuf:"varint,1,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueueDepth     int32                  `protobuf:"varint,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	QueueCapacity  int32                  `protobuf:"varint,3,opt,name=queue_capacity,json=queueCapacity,proto3" json:"queue_capacity,omitempty"`
	TasksProcessed int64                  `protobuf:"varint,4,opt,name=tasks_processed,json=tasksProcessed,proto3" json:"tasks_processed,omitempty"`
	TaskErrors     int64                  `protobuf:"varint,5,opt,name=task_errors,json=taskErrors,proto3" json:"task_errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerPoolStats) Reset() {
	*x = WorkerPoolStats{}
	mi := &file_proto_admin_admin_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerPoolStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerPoolStats) ProtoMessage() {}

func (x *WorkerPoolStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerPoolStats.ProtoReflect.Descriptor instead.
func (*WorkerPoolStats) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_health_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerPoolStats) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *WorkerPoolStats) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *WorkerPoolStats) GetQueueCapacity() int32 {
	if x != nil {
		return x.QueueCapacity
	}
	return 0
}

func (x *WorkerPoolStats) GetTasksProcessed() int64 {
	if x != nil {
		return x.TasksProcessed
	}
	return 0
}

func (x *WorkerPoolStats) GetTaskErrors() int64 {
	if x != nil {
		return x.TaskErrors
	}
	return 0
}

type FlowControlConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxInflightTotal     int32                  `protobuf:"varint,1,opt,name=max_inflight_total,json=maxInflightTotal,proto3" json:"max_inflight_total,omitempty"`
	MaxInflightCommand   int32                  `protobuf:"varint,2,opt,name=max_inflight_command,json=maxInflightCommand,proto3" json:"max_inflight_command,omitempty"`
	MaxInflightControl   int32                  `protobuf:"varint,3,opt,name=max_inflight_control,json=maxInflightControl,proto3" json:"max_inflight_control,omitempty"`
	MaxInflightTelemetry int32                  `protobuf:"varint,4,opt,name=max_inflight_telemetry,json=maxInflightTelemetry,proto3" json:"max_inflight_telemetry,omitempty"`
	MaxBatchBytes        int32                  `protobuf:"varint,5,opt,name=max_batch_bytes,json=maxBatchBytes,proto3" json:"max_batch_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FlowControlConfig) Reset() {
	*x = FlowControlConfig{}
	mi := &file_proto_admin_admin_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowControlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowControlConfig) ProtoMessage() {}

func (x *FlowControlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowControlConfig.ProtoReflect.Descriptor instead.
func (*FlowControlConfig) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_health_proto_rawDescGZIP(), []int{3}
}

func (x *FlowControlConfig) GetMaxInflightTotal() int32 {
	if x != nil {
		return x.MaxInflightTotal
	}
	return 0
}

func (x *FlowControlConfig) GetMaxInflightCommand() int32 {
	if x != nil {
		return x.MaxInflightCommand
	}
	return 0
}

func (x *FlowControlConfig) GetMaxInflightControl() int32 {
	if x != nil {
		return x.MaxInflightControl
	}
	return 0
}

func (x *FlowControlConfig) GetMaxInflightTelemetry() int32 {
	if x != nil {
		return x.MaxInflightTelemetry
	}
	return 0
}

func (x *FlowControlConfig) GetMaxBatchBytes() int32 {
	if x != nil {
		return x.MaxBatchBytes
	}
	return 0
}

var File_proto_admin_admin_health_proto protoreflect.FileDescriptor

const file_proto_admin_admin_health_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/admin/admin_health.proto\x12\n" +
	"spineadmin\x1a\x18proto/admin/common.proto\"\xb1\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12'\n" +
	"\x0ftotal_mailboxes\x18\x03 \x01(\x03R\x0etotalMailboxes\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\xe5\x03\n" +
	"\x14HealthDetailResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12'\n" +
	"\x0ftotal_mailboxes\x18\x03 \x01(\x03R\x0etotalMailboxes\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12T\n" +
	"\fworker_pools\x18\x06 \x03(\v21.spineadmin.HealthDetailResponse.WorkerPoolsEntryR\vworkerPools\x12@\n" +
	"\fflow_control\x18\a \x01(\v2\x1d.spineadmin.FlowControlConfigR\vflowControl\x12\x1f\n" +
	"\vtls_enabled\x18\b \x01(\bR\n" +
	"tlsEnabled\x12\x1b\n" +
	"\tmtls_mode\x18\t \x01(\tR\bmtlsMode\x1a[\n" +
	"\x10WorkerPoolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.spineadmin.WorkerPoolStatsR\x05value:\x028\x01\"\xca\x01\n" +
	"\x0fWorkerPoolStats\x12%\n" +
	"\x0eactive_workers\x18\x01 \x01(\x05R\ractiveWorkers\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\x05R\n" +
	"queueDepth\x12%\n" +
	"\x0equeue_capacity\x18\x03 \x01(\x05R\rqueueCapacity\x12'\n" +
	"\x0ftasks_processed\x18\x04 \x01(\x03R\x0etasksProcessed\x12\x1f\n" +
	"\vtask_errors\x18\x05 \x01(\x03R\n" +
	"taskErrors\"\x83\x02\n" +
	"\x11FlowControlConfig\x12,\n" +
	"\x12max_inflight_total\x18\x01 \x01(\x05R\x10maxInflightTotal\x120\n" +
	"\x14max_inflight_command\x18\x02 \x01(\x05R\x12maxInflightCommand\x120\n" +
	"\x14max_inflight_control\x18\x03 \x01(\x05R\x12maxInflightControl\x124\n" +
	"\x16max_inflight_telemetry\x18\x04 \x01(\x05R\x14maxInflightTelemetry\x12&\n" +
	"\x0fmax_batch_bytes\x18\x05 \x01(\x05R\rmaxBatchBytes2\x94\x01\n" +
	"\x12AdminHealthService\x12=\n" +
	"\x05Check\x12\x11.spineadmin.Empty\x1a\x1f.spineadmin.HealthCheckResponse\"\x00\x12?\n" +
	"\x06Detail\x12\x11.spineadmin.Empty\x1a .spineadmin.HealthDetailResponse\"\x00BBZ@github.com/ambientlabscomputing/mycelium_spine/proto/admin;adminb\x06proto3"

var (
	file_proto_admin_admin_health_proto_rawDescOnce sync.Once
	file_proto_admin_admin_health_proto_rawDescData []byte
)

func file_proto_admin_admin_health_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_health_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_health_proto_rawDesc), len(file_proto_admin_admin_health_proto_rawDesc)))
	})
	return file_proto_admin_admin_health_proto_rawDescData
}

var file_proto_admin_admin_health_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_admin_admin_health_proto_goTypes = []any{
	(*HealthCheckResponse)(nil),  // 0: spineadmin.HealthCheckResponse
	(*HealthDetailResponse)(nil), // 1: spineadmin.HealthDetailResponse
	(*WorkerPoolStats)(nil),      // 2: spineadmin.WorkerPoolStats
	(*FlowControlConfig)(nil),    // 3: spineadmin.FlowControlConfig
	nil,                          // 4: spineadmin.HealthDetailResponse.WorkerPoolsEntry
	(*Empty)(nil),                // 5: spineadmin.Empty
}
var file_proto_admin_admin_health_proto_depIdxs = []int32{
	4, // 0: spineadmin.HealthDetailResponse.worker_pools:type_name -> spineadmin.HealthDetailResponse.WorkerPoolsEntry
	3, // 1: spineadmin.HealthDetailResponse.flow_control:type_name -> spineadmin.FlowControlConfig
	2, // 2: spineadmin.HealthDetailResponse.WorkerPoolsEntry.value:type_name -> spineadmin.WorkerPoolStats
	5, // 3: spineadmin.AdminHealthService.Check:input_type -> spineadmin.Empty
	5, // 4: spineadmin.AdminHealthService.Detail:input_type -> spineadmin.Empty
	0, // 5: spineadmin.AdminHealthService.Check:output_type -> spineadmin.HealthCheckResponse
	1, // 6: spineadmin.AdminHealthService.Detail:output_type -> spineadmin.HealthDetailResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_health_proto_init() }
func file_proto_admin_admin_health_proto_init() {
	if File_proto_admin_admin_health_proto != nil {
		return
	}
	file_proto_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_health_proto_rawDesc), len(file_proto_admin_admin_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_health_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_health_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_health_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_health_proto = out.File
	file_proto_admin_admin_health_proto_goTypes = nil
	file_proto_admin_admin_health_proto_depIdxs = nil
}
