// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admin/admin_sessions.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"` // Optional filter
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`             // 0 = default (50)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *ListSessionsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SessionSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrgId             string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SessionEpoch      uint64                 `protobuf:"varint,4,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	SubscriptionCount int32                  `protobuf:"varint,5,opt,name=subscription_count,json=subscriptionCount,proto3" json:"subscription_count,omitempty"`
	ConnectedAt       string                 `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastHeartbeat     string                 `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *SessionSummary) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SessionSummary) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *SessionSummary) GetSubscriptionCount() int32 {
	if x != nil {
		return x.SubscriptionCount
	}
	return 0
}

func (x *SessionSummary) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *SessionSummary) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of session_id or server_id must be set.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId      string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type SessionDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrgId             string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SessionEpoch      uint64                 `protobuf:"varint,4,opt,name=session_epoch,json=sessionEpoch,proto3" json:"session_epoch,omitempty"`
	Subscriptions     []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	ConnectedAt       string                 `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastHeartbeat     string                 `protobuf:"bytes,7,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	DeviceFingerprint string                 `protobuf:"bytes,8,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	ClientFeatures    map[string]bool        `protobuf:"bytes,9,rep,name=client_features,json=clientFeatures,proto3" json:"client_features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionDetail) Reset() {
	*x = SessionDetail{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDetail) ProtoMessage() {}

func (x *SessionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDetail.ProtoReflect.Descriptor instead.
func (*SessionDetail) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *SessionDetail) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SessionDetail) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionDetail) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SessionDetail) GetSessionEpoch() uint64 {
	if x != nil {
		return x.SessionEpoch
	}
	return 0
}

func (x *SessionDetail) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *SessionDetail) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *SessionDetail) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *SessionDetail) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *SessionDetail) GetClientFeatures() map[string]bool {
	if x != nil {
		return x.ClientFeatures
	}
	return nil
}

type DisconnectSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of session_id or server_id must be set.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerId      string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectSessionRequest) Reset() {
	*x = DisconnectSessionRequest{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectSessionRequest) ProtoMessage() {}

func (x *DisconnectSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectSessionRequest.ProtoReflect.Descriptor instead.
func (*DisconnectSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectSessionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type EvictStaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EvictedCount  int32                  `protobuf:"varint,1,opt,name=evicted_count,json=evictedCount,proto3" json:"evicted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvictStaleResponse) Reset() {
	*x = EvictStaleResponse{}
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvictStaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictStaleResponse) ProtoMessage() {}

func (x *EvictStaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_sessions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictStaleResponse.ProtoReflect.Descriptor instead.
func (*EvictStaleResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *EvictStaleResponse) GetEvictedCount() int32 {
	if x != nil {
		return x.EvictedCount
	}
	return 0
}

var File_proto_admin_admin_sessions_proto protoreflect.FileDescriptor

const file_proto_admin_admin_sessions_proto_rawDesc = "" +
	"\n" +
	" proto/admin/admin_sessions.proto\x12\n" +
	"spineadmin\x1a\x18proto/admin/common.proto\"Z\n" +
	"\x13ListSessionsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x86\x01\n" +
	"\x14ListSessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.spineadmin.SessionSummaryR\bsessions\x126\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.spineadmin.PaginationR\n" +
	"pagination\"\x81\x02\n" +
	"\x0eSessionSummary\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12#\n" +
	"\rsession_epoch\x18\x04 \x01(\x04R\fsessionEpoch\x12-\n" +
	"\x12subscription_count\x18\x05 \x01(\x05R\x11subscriptionCount\x12!\n" +
	"\fconnected_at\x18\x06 \x01(\tR\vconnectedAt\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\tR\rlastHeartbeat\"O\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"\xc1\x03\n" +
	"\rSessionDetail\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12#\n" +
	"\rsession_epoch\x18\x04 \x01(\x04R\fsessionEpoch\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12!\n" +
	"\fconnected_at\x18\x06 \x01(\tR\vconnectedAt\x12%\n" +
	"\x0elast_heartbeat\x18\a \x01(\tR\rlastHeartbeat\x12-\n" +
	"\x12device_fingerprint\x18\b \x01(\tR\x11deviceFingerprint\x12V\n" +
	"\x0fclient_features\x18\t \x03(\v2-.spineadmin.SessionDetail.ClientFeaturesEntryR\x0eclientFeatures\x1aA\n" +
	"\x13ClientFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"V\n" +
	"\x18DisconnectSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"9\n" +
	"\x12EvictStaleResponse\x12#\n" +
	"\revicted_count\x18\x01 \x01(\x05R\fevictedCount2\xb2\x02\n" +
	"\x14AdminSessionsService\x12K\n" +
	"\x04List\x12\x1f.spineadmin.ListSessionsRequest\x1a .spineadmin.ListSessionsResponse\"\x00\x12A\n" +
	"\x03Get\x12\x1d.spineadmin.GetSessionRequest\x1a\x19.spineadmin.SessionDetail\"\x00\x12G\n" +
	"\n" +
	"Disconnect\x12$.spineadmin.DisconnectSessionRequest\x1a\x11.spineadmin.Empty\"\x00\x12A\n" +
	"\n" +
	"EvictStale\x12\x11.spineadmin.Empty\x1a\x1e.spineadmin.EvictStaleResponse\"\x00BBZ@github.com/ambientlabscomputing/mycelium_spine/proto/admin;adminb\x06proto3"

var (
	file_proto_admin_admin_sessions_proto_rawDescOnce sync.Once
	file_proto_admin_admin_sessions_proto_rawDescData []byte
)

func file_proto_admin_admin_sessions_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_sessions_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_sessions_proto_rawDesc), len(file_proto_admin_admin_sessions_proto_rawDesc)))
	})
	return file_proto_admin_admin_sessions_proto_rawDescData
}

var file_proto_admin_admin_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_admin_admin_sessions_proto_goTypes = []any{
	(*ListSessionsRequest)(nil),      // 0: spineadmin.ListSessionsRequest
	(*ListSessionsResponse)(nil),     // 1: spineadmin.ListSessionsResponse
	(*SessionSummary)(nil),           // 2: spineadmin.SessionSummary
	(*GetSessionRequest)(nil),        // 3: spineadmin.GetSessionRequest
	(*SessionDetail)(nil),            // 4: spineadmin.SessionDetail
	(*DisconnectSessionRequest)(nil), // 5: spineadmin.DisconnectSessionRequest
	(*EvictStaleResponse)(nil),       // 6: spineadmin.EvictStaleResponse
	nil,                              // 7: spineadmin.SessionDetail.ClientFeaturesEntry
	(*Pagination)(nil),               // 8: spineadmin.Pagination
	(*Empty)(nil),                    // 9: spineadmin.Empty
}
var file_proto_admin_admin_sessions_proto_depIdxs = []int32{
	2, // 0: spineadmin.ListSessionsResponse.sessions:type_name -> spineadmin.SessionSummary
	8, // 1: spineadmin.ListSessionsResponse.pagination:type_name -> spineadmin.Pagination
	7, // 2: spineadmin.SessionDetail.client_features:type_name -> spineadmin.SessionDetail.ClientFeaturesEntry
	0, // 3: spineadmin.AdminSessionsService.List:input_type -> spineadmin.ListSessionsRequest
	3, // 4: spineadmin.AdminSessionsService.Get:input_type -> spineadmin.GetSessionRequest
	5, // 5: spineadmin.AdminSessionsService.Disconnect:input_type -> spineadmin.DisconnectSessionRequest
	9, // 6: spineadmin.AdminSessionsService.EvictStale:input_type -> spineadmin.Empty
	1, // 7: spineadmin.AdminSessionsService.List:output_type -> spineadmin.ListSessionsResponse
	4, // 8: spineadmin.AdminSessionsService.Get:output_type -> spineadmin.SessionDetail
	9, // 9: spineadmin.AdminSessionsService.Disconnect:output_type -> spineadmin.Empty
	6, // 10: spineadmin.AdminSessionsService.EvictStale:output_type -> spineadmin.EvictStaleResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_sessions_proto_init() }
func file_proto_admin_admin_sessions_proto_init() {
	if File_proto_admin_admin_sessions_proto != nil {
		return
	}
	file_proto_admin_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_sessions_proto_rawDesc), len(file_proto_admin_admin_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_sessions_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_sessions_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_sessions_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_sessions_proto = out.File
	file_proto_admin_admin_sessions_proto_goTypes = nil
	file_proto_admin_admin_sessions_proto_depIdxs = nil
}
