// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin/admin_mailboxes.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminMailboxesService_List_FullMethodName          = "/spineadmin.AdminMailboxesService/List"
	AdminMailboxesService_Get_FullMethodName           = "/spineadmin.AdminMailboxesService/Get"
	AdminMailboxesService_ListEnvelopes_FullMethodName = "/spineadmin.AdminMailboxesService/ListEnvelopes"
	AdminMailboxesService_PurgeExpired_FullMethodName  = "/spineadmin.AdminMailboxesService/PurgeExpired"
	AdminMailboxesService_ClearOutbox_FullMethodName   = "/spineadmin.AdminMailboxesService/ClearOutbox"
)

// AdminMailboxesServiceClient is the client API for AdminMailboxesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminMailboxesServiceClient interface {
	List(ctx context.Context, in *ListMailboxesRequest, opts ...grpc.CallOption) (*ListMailboxesResponse, error)
	Get(ctx context.Context, in *GetMailboxRequest, opts ...grpc.CallOption) (*MailboxDetail, error)
	ListEnvelopes(ctx context.Context, in *ListEnvelopesRequest, opts ...grpc.CallOption) (*ListEnvelopesResponse, error)
	PurgeExpired(ctx context.Context, in *PurgeExpiredRequest, opts ...grpc.CallOption) (*PurgeExpiredResponse, error)
	ClearOutbox(ctx context.Context, in *ClearOutboxRequest, opts ...grpc.CallOption) (*ClearOutboxResponse, error)
}

type adminMailboxesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminMailboxesServiceClient(cc grpc.ClientConnInterface) AdminMailboxesServiceClient {
	return &adminMailboxesServiceClient{cc}
}

func (c *adminMailboxesServiceClient) List(ctx context.Context, in *ListMailboxesRequest, opts ...grpc.CallOption) (*ListMailboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMailboxesResponse)
	err := c.cc.Invoke(ctx, AdminMailboxesService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminMailboxesServiceClient) Get(ctx context.Context, in *GetMailboxRequest, opts ...grpc.CallOption) (*MailboxDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MailboxDetail)
	err := c.cc.Invoke(ctx, AdminMailboxesService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminMailboxesServiceClient) ListEnvelopes(ctx context.Context, in *ListEnvelopesRequest, opts ...grpc.CallOption) (*ListEnvelopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvelopesResponse)
	err := c.cc.Invoke(ctx, AdminMailboxesService_ListEnvelopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminMailboxesServiceClient) PurgeExpired(ctx context.Context, in *PurgeExpiredRequest, opts ...grpc.CallOption) (*PurgeExpiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeExpiredResponse)
	err := c.cc.Invoke(ctx, AdminMailboxesService_PurgeExpired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminMailboxesServiceClient) ClearOutbox(ctx context.Context, in *ClearOutboxRequest, opts ...grpc.CallOption) (*ClearOutboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearOutboxResponse)
	err := c.cc.Invoke(ctx, AdminMailboxesService_ClearOutbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminMailboxesServiceServer is the server API for AdminMailboxesService service.
// All implementations must embed UnimplementedAdminMailboxesServiceServer
// for forward compatibility.
type AdminMailboxesServiceServer interface {
	List(context.Context, *ListMailboxesRequest) (*ListMailboxesResponse, error)
	Get(context.Context, *GetMailboxRequest) (*MailboxDetail, error)
	ListEnvelopes(context.Context, *ListEnvelopesRequest) (*ListEnvelopesResponse, error)
	PurgeExpired(context.Context, *PurgeExpiredRequest) (*PurgeExpiredResponse, error)
	ClearOutbox(context.Context, *ClearOutboxRequest) (*ClearOutboxResponse, error)
	mustEmbedUnimplementedAdminMailboxesServiceServer()
}

// UnimplementedAdminMailboxesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminMailboxesServiceServer struct{}

func (UnimplementedAdminMailboxesServiceServer) List(context.Context, *ListMailboxesRequest) (*ListMailboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminMailboxesServiceServer) Get(context.Context, *GetMailboxRequest) (*MailboxDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAdminMailboxesServiceServer) ListEnvelopes(context.Context, *ListEnvelopesRequest) (*ListEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvelopes not implemented")
}
func (UnimplementedAdminMailboxesServiceServer) PurgeExpired(context.Context, *PurgeExpiredRequest) (*PurgeExpiredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeExpired not implemented")
}
func (UnimplementedAdminMailboxesServiceServer) ClearOutbox(context.Context, *ClearOutboxRequest) (*ClearOutboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearOutbox not implemented")
}
func (UnimplementedAdminMailboxesServiceServer) mustEmbedUnimplementedAdminMailboxesServiceServer() {}
func (UnimplementedAdminMailboxesServiceServer) testEmbeddedByValue()                               {}

// UnsafeAdminMailboxesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminMailboxesServiceServer will
// result in compilation errors.
type UnsafeAdminMailboxesServiceServer interface {
	mustEmbedUnimplementedAdminMailboxesServiceServer()
}

func RegisterAdminMailboxesServiceServer(s grpc.ServiceRegistrar, srv AdminMailboxesServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminMailboxesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminMailboxesService_ServiceDesc, srv)
}

func _AdminMailboxesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMailboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMailboxesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMailboxesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMailboxesServiceServer).List(ctx, req.(*ListMailboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminMailboxesService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMailboxesServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMailboxesService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMailboxesServiceServer).Get(ctx, req.(*GetMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminMailboxesService_ListEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMailboxesServiceServer).ListEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMailboxesService_ListEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMailboxesServiceServer).ListEnvelopes(ctx, req.(*ListEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminMailboxesService_PurgeExpired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeExpiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMailboxesServiceServer).PurgeExpired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMailboxesService_PurgeExpired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMailboxesServiceServer).PurgeExpired(ctx, req.(*PurgeExpiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminMailboxesService_ClearOutbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearOutboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminMailboxesServiceServer).ClearOutbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminMailboxesService_ClearOutbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminMailboxesServiceServer).ClearOutbox(ctx, req.(*ClearOutboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminMailboxesService_ServiceDesc is the grpc.ServiceDesc for AdminMailboxesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminMailboxesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spineadmin.AdminMailboxesService",
	HandlerType: (*AdminMailboxesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AdminMailboxesService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AdminMailboxesService_Get_Handler,
		},
		{
			MethodName: "ListEnvelopes",
			Handler:    _AdminMailboxesService_ListEnvelopes_Handler,
		},
		{
			MethodName: "PurgeExpired",
			Handler:    _AdminMailboxesService_PurgeExpired_Handler,
		},
		{
			MethodName: "ClearOutbox",
			Handler:    _AdminMailboxesService_ClearOutbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin_mailboxes.proto",
}
