// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/admin/admin_health.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminHealthService_Check_FullMethodName  = "/spineadmin.AdminHealthService/Check"
	AdminHealthService_Detail_FullMethodName = "/spineadmin.AdminHealthService/Detail"
)

// AdminHealthServiceClient is the client API for AdminHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminHealthServiceClient interface {
	Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Detail(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthDetailResponse, error)
}

type adminHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminHealthServiceClient(cc grpc.ClientConnInterface) AdminHealthServiceClient {
	return &adminHealthServiceClient{cc}
}

func (c *adminHealthServiceClient) Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AdminHealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminHealthServiceClient) Detail(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthDetailResponse)
	err := c.cc.Invoke(ctx, AdminHealthService_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminHealthServiceServer is the server API for AdminHealthService service.
// All implementations must embed UnimplementedAdminHealthServiceServer
// for forward compatibility.
type AdminHealthServiceServer interface {
	Check(context.Context, *Empty) (*HealthCheckResponse, error)
	Detail(context.Context, *Empty) (*HealthDetailResponse, error)
	mustEmbedUnimplementedAdminHealthServiceServer()
}

// UnimplementedAdminHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminHealthServiceServer struct{}

func (UnimplementedAdminHealthServiceServer) Check(context.Context, *Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAdminHealthServiceServer) Detail(context.Context, *Empty) (*HealthDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedAdminHealthServiceServer) mustEmbedUnimplementedAdminHealthServiceServer() {}
func (UnimplementedAdminHealthServiceServer) testEmbeddedByValue()                            {}

// UnsafeAdminHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminHealthServiceServer will
// result in compilation errors.
type UnsafeAdminHealthServiceServer interface {
	mustEmbedUnimplementedAdminHealthServiceServer()
}

func RegisterAdminHealthServiceServer(s grpc.ServiceRegistrar, srv AdminHealthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminHealthService_ServiceDesc, srv)
}

func _AdminHealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminHealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminHealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminHealthServiceServer).Check(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminHealthService_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminHealthServiceServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminHealthService_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminHealthServiceServer).Detail(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminHealthService_ServiceDesc is the grpc.ServiceDesc for AdminHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spineadmin.AdminHealthService",
	HandlerType: (*AdminHealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _AdminHealthService_Check_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _AdminHealthService_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/admin_health.proto",
}
